### ISSUE TITLE
Restricting content after the <!--more--> tag

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#1]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

**Markdown File:** http://wsharks.com/1CzJL2G
**Published KB Article:** http://s2member.com/kb-article/restricting-content-after-the-tag/

---

**Comment by peoyli** [comment]
that s2if-code is broken ... 
shoudl be:

    ```
$pos1 = strpos($content, '<span id="more-');
    if ($pos1 !== false)
    {
      $pos2 = strpos($content, '</span>', $pos1);
      $before_more_tag = substr($content, 0, $pos2);
      $after_more_tag = substr($content, $pos2);
      $content = $before_more_tag . $s2if_start . $s2if_message . $after_more_tag . $s2if_end;
    }
```
otherwise all posts NOT containing <span id="more-".. will also be protected.. been there, done that..

**Comment by raamdev** [comment]
@peoyli Thanks! 😄  I've updated the code example.

**Comment by peoyli** [comment]
it's not updated here, where I found it the first time:
https://s2member.com/kb-article/restricting-content-after-the-tag/

It could also be improved a bit more by adding && is_single() to that if-statement:
if ($pos1 !== false && is_single())

(or to save some microseconds of processing time as a separate if-statement before the search for the "<!--more"-tag)
