### ISSUE TITLE
Using the E-Mail address as the Username

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#10]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

**Markdown File:** http://wsharks.com/1Czzuni
**Published KB Article:** http://s2member.com/kb-article/using-the-e-mail-address-as-the-username/

---

**Comment by milehigh420** [comment]
Raamdev, it says that this code hasn't been tested in a few years. As far as you know is that still accurate? 

And then I wanted to ask, I'm a little confused when when people refer to s2 pro forms. Is that the just the pro version of S2? Or is that a reference to the Paypal pro forms? Confusing.

I have the pro version of s2, but am not using paypal pro forms. I built my form with the Custom Registration/Profile Fields and have that set as a free form linked to mailchimp with krumch plugin.

So I'm curious if the first approach listed here will work. Can you confirm this please?

**Comment by milehigh420** [comment]
I tried it out and it works. But for a second I see the username field and then it disappears. Do you know how I can eliminate this?

And now the first name is between the password field and last name. It looks weird. Is there a way to adjust this?

Thanks for any help you can give, really appreciate it!

**Comment by raamdev** [comment]
@milehigh420 writes...

> And then I wanted to ask, I'm a little confused when when people refer to s2 pro forms. Is that the just the pro version of S2? Or is that a reference to the Paypal pro forms? Confusing.
>
> I have the pro version of s2, but am not using paypal pro forms. I built my form with the Custom Registration/Profile Fields and have that set as a free form linked to mailchimp with krumch plugin.
> 
> So I'm curious if the first approach listed here will work. Can you confirm this please?

Pro-Forms are a feature of s2Member Pro, but PayPal Pro is not required. In fact, s2Member Pro comes with Pro-Forms for many different payment gateways, not just PayPal.

To use the technique described in this article, you'll need to be using Pro-Forms. If you just want to create a Free Registration form, please see `s2Member ⥱ PayPal Pro-Forms ⥱ PayPal Pro / Free Registration Forms`. You can use the technique described in this article for Free Registration Forms.

> And now the first name is between the password field and last name. It looks weird. Is there a way to adjust this?

That all depends on your specific theme. You should be able to fix this with some CSS and/or JavaScript. What you use will be specific to your theme. If you need help with that, I recommend posting a question on the [WordPress Support Forum](http://wordpress.org/support/).

**Comment by milehigh420** [comment]
Raamdev,
Thanks for the reply.
But any idea why the username displays for a second and then disappears? Is this also a CSS/javascript issue related to my theme?

I'm worried that if the username is there for a second, that someone could type something in, and that could screw things up when the form is submitted. Not to mention it looks bad.

Thanks.

And I'll make a post on wordpress site about per your recommendation.

**Comment by raamdev** [comment]
> But any idea why the username displays for a second and then disappears? Is this also a CSS/javascript issue related to my theme?

This is due to how the field is being hidden--the JavaScript is loading _after_ the form loads, so you see the field for a second.

You could try adding `#s2member-pro-paypal-checkout-form-username-div { display: none !important; }` to your theme's `style.css` file; that should hide the field before it's seen.

Otherwise, you could always customize the Pro-Form template itself; see [Customizing Pro-Forms](http://www.s2member.com/kb/pro-forms/#customizing-pro-forms).

**Comment by milehigh420** [comment]
Really appreciate the help raamdev!

I added the CSS to style.css and it didn't change the fact that the username appears for a few seconds and then disappears.

So I was thinking about editing the pro-form template as you suggest. See I've been using the free registration form link located in General Options> Registration Field Options. /wp-login.php?action=register. I guess that's not a pro form.

So I got to the Free Pro Forms sections. And insert the registration shortcode. I like how this is embedded in my site and has better captcha. But it doesn't hide the username at all on this registration.  And I tried to register and it says the username is required now.

Do you know why it isn't hiding the username at all on this Pro Form? Or am misunderstanding something.

Thank you so much. I'm so close to getting these forms to where they need to be.

**Comment by raamdev** [comment]
> Do you know why it isn't hiding the username at all on this Pro Form? Or am misunderstanding something.

That would indicate you haven't setup the hack properly, or that there's something wrong with the code above. As I noted in the original post, the code hasn't been tested in a few years.

This GitHub Issue is just a draft for this KB Article. When we get around to finishing this KB Article and publishing it on our website, the code will be fully tested before it is published. Until then, if you're not comfortable with programming and debugging code and you need help with this, I recommend hiring a programmer. 

We reserve GitHub for filing bug reports and this specific GitHub Repo (`s2member-kb`) is reserved for writing drafts of new KB Articles.
