### ISSUE TITLE
How do I switch between multiple video qualities when using the [s2Stream /] shortcode and JW Player?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#102]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

**Markdown File:** http://wsharks.com/1DGmlJ2
**Published KB Article:** http://s2member.com/kb-article/how-do-i-switch-between-multiple-video-qualities-when-using-the-s2stream-shortcode-and-jw-player/

---

**Comment by jaswsinc** [comment]
We should add a screenshot in this article that shows how to switch between different resolutions in JW Player; i.e., a screenshot of the little HD icon that provides the various options that a site owner makes available.

**Comment by raamdev** [comment]
@jaswsinc Copy that. I'm adding this to my TODO list for this week.
