### ISSUE TITLE
Do tax configurations work with payment "buttons"?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#107]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

**Markdown File:** http://wsharks.com/1GIncKa
**Published KB Article:** http://s2member.com/kb-article/do-tax-configurations-work-with-payment-buttons/

---

**Comment by raamdev** [comment]
Updated `tags:` in the YAML config to use `tax-rate-calculations-pro-form` instead of `tax-configuration` (the former being the name of the relevant options panel).

**Comment by jaswsinc** [comment]
Copy that. Thanks!

**Comment by kristineds** [comment]
> Please see: `s2Member → PayPal Pro-Forms → Tax Rate Calculations`

@jaswsinc @raamdev: I found the configuration settings for Tax Rate Calculations under "Paypal Options" and not "Paypal Pro-Forms" as seen on the KB article. :)

**Comment by jaswsinc** [comment]
@kristineds Thanks! I updated the article.
http://s2member.com/kb-article/do-tax-configurations-work-with-payment-buttons/
