### ISSUE TITLE
Does s2Member send a payment receipt or invoice?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#108]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

**Markdown File:** http://wsharks.com/195d8fs
**Published KB Article:** http://s2member.com/kb-article/does-s2member-send-a-payment-receipt-or-invoice/

---

**Comment by jaswsinc** [comment]
We should probably explain that a Signup Confirmation Email can be customized in such a way that it can serve as an email receipt/invoice; i.e., there are enough Replacement Codes supplied by s2Member to accomplish this.
