### ISSUE TITLE
Where can I download old versions of s2Member?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#11]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODO Items

- [x] Update links that lead to the archive once the archives exist on the new site.
- [x] The archive for the free version needs to be available to the public; I believe it already is.

---

[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/11-where-can-i-download-old-versions-of-s2member.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/11-where-can-i-download-old-versions-of-s2member.md)
:page_with_curl: **Published KB Article:** http://s2member.com/kb-article/where-can-i-download-old-versions-of-s2member/

---

**Comment by jaswsinc** [comment]
Updated and published.
