### ISSUE TITLE
How do I allow change only empty custom fields?

### ISSUE THREAD

**Issue by jozephbrasil** [websharks/s2member-kb#110]
I would like to allow some custom fields to be changed, but only if they are empty. Is it possible?

**Comment by jaswsinc** [comment]
We reserve GitHub for discussions regarding the s2Member source code, detailed bug reports, and feature requests. Customer service and technical support for s2Member are handled by our support team. Please open a trouble ticket here. We'll be happy to assist you there :-) Please visit: http://wsharks.com/1pYbliq

**Comment by jaswsinc** [comment]
See also: https://github.com/websharks/s2member-kb/blob/master/CONTRIBUTING.md
