### ISSUE TITLE
How to validate custom fields?

### ISSUE THREAD

**Issue by jozephbrasil** [websharks/s2member-kb#111]
There is a custom field that I need to validate using some rules. How to do it?
PS: need to be validate (checked) in registration form and update profile.

**Comment by jaswsinc** [comment]
We reserve GitHub for discussions regarding the s2Member source code, detailed bug reports, and feature requests. Customer service and technical support for s2Member are handled by our support team. Please open a trouble ticket here. We'll be happy to assist you there :-) Please visit: http://wsharks.com/1pYbliq

**Comment by jaswsinc** [comment]
See also: https://github.com/websharks/s2member-kb/blob/master/CONTRIBUTING.md
