### ISSUE TITLE
Adding Custom Mail Merge Tags (Custom Fields) for MailChimp, AWeber, GetResponse

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#114]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

**Markdown File:** http://wsharks.com/1GImk84
**Published KB Article:** http://s2member.com/kb-article/adding-custom-mail-merge-tags-custom-fields-mailchimp-aweber-getresponse/

---

**Comment by Ute11** [comment]
Thank you so much! 
This feature will allow for detailed list segmentation which is absolutely fantastic!

**Comment by petervangorder** [comment]
The article says "Read over the instructions in the code below, and adjust as necessary."
But there are no instructions, just a note to create the merge tags in Mailchimp.
It does not say if I need to the merge tags to this array or what my next steps are.
For example;  Do I need to make the MailChimp merge tags the same names as my custom capabilities? what if there are spaces?  I'm noticing that the merge tags in MailChimp have a field label and then a shortened version of that label in all caps.   Does this matter?

**Comment by Ute11** [comment]
Here is how I have set up the mailchimp list field for ccaps. I hope that helps @petervangorder 
![mailchimpsetting](https://cloud.githubusercontent.com/assets/11184411/8052105/3288d708-0e84-11e5-889b-edb5bff94275.jpg)

**Comment by jaswsinc** [comment]
Thanks for the feedback :-)
I updated the article so that it includes a MailChimp screenshot.
http://s2member.com/kb-article/can-i-add-custom-mail-merge-fields/

![2015-06-09_03-21-23](https://cloud.githubusercontent.com/assets/1563559/8056672/e93982be-0e56-11e5-87b6-5dad7f666d70.png)
