### ISSUE TITLE
Can I Change Pro Login Widget Form action?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#117]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

**Markdown File:** http://wsharks.com/1Mvy6Do
**Published KB Article:** http://s2member.com/kb-article/can-i-change-pro-login-widget-form-action/

---

**Comment by imranlaldin** [comment]
Hi, 

i did as follow, but its useless. Even when i login, it redirect to the same page again. 

Everything is setup properly,  but what i asked, its not work. 

I said, i created a page  for login 
http://norgesavisen.no/dev/logg-inn/   

if wrong password entered, than the error msg should be visible on same page.  not redirect to wp-login.php 

see screen shot if wrong password entered. 
http://awesomescreenshot.com/0304jqel91

**Comment by jaswsinc** [comment]
@imranlaldin Thank you for the feedback.

I made some adjustments to the script above so it will do a better job of adjusting the form action.

The purpose of this article will be to show how you can alter the `<form action="">` that is used by the s2Member Pro Login Widget. The default behavior is to use the existing `wp-login.php` file in WordPress, as this maximizes compatibility across a wide array of themes/plugins for WordPress. Including, but not limited to BuddyPress, bbPress, and many plugins that implement things like CAPTCHAs, Single Sign-On, custom error messages, etc.

The s2Member Pro Login Widget is intentionally not designed to implement it's own handler for password retrieval, or a default UI when login fails, as this is something that most themes/plugins expect `/wp-login.php` to be used for as part of the WordPress core.

However, with the filter above, you can change the form action. This is useful if you intend to implement your own custom login handler, or integrate the s2Member Pro Login Widget with another 3rd-party component. It should be of assistance in that way.

If you don't have a custom login handler of your own, you might try searching the WordPress.org plugins repository for AJAX-based login widgets. There is a plugin called [Sidebar Login](https://wordpress.org/plugins/sidebar-login/) which was last tested about a year ago with s2Member and it has worked well for many s2Member site owners. I just ran another quick test to confirm, and it appears to be in good working order. Might be worth a shot :-)

**Comment by imranlaldin** [comment]
Hi, 
Thanks for your help, but unfortunately your code again not working. 

it redirect me to the login page even if i give correct password. 
http://norgesavisen.no/dev/logg-inn/   this is  my login page. 

u can test  user =  imran   password  = hello1234 

when i entered correct password, it redirect to me on same page. 

i requested you that,  if Wrong password entered, it should not show me the wp-login.php , 

it should go to /logg-inn/ page with error msg.  

For your information,  on Logg-inn page, i am using the side bar login widget code. so is there any way to get this done. ?

**Comment by Martin-1** [comment]
I used this:

add_action( 'wp_login_failed', 'my_front_end_login_fail' );  // hook failed login

function my_front_end_login_fail( $username ) {
   $referrer = $_SERVER['HTTP_REFERER'];  // where did the post submission come from?
   // if there's a valid referrer, and it's not the default log-in screen
   if ( !empty($referrer) && !strstr($referrer,'wp-login') && !strstr($referrer,'wp-admin') ) {
      wp_redirect( $referrer . '?login=failed' );  // let's append some information (login=failed) to the URL for the theme to use
      exit;
   }
}

This seems to work. Only NOT when one or both fields are left empty. Then it redirects to the official wp login page. Not sure why and I can't seem to solve that issue myself, but at least it gets you a bit further I hope :-).

**Comment by imranlaldin** [comment]
it still not work. 

but you actually didn't read my quires properly. i think. 

i again try to explain it to you. 

We created a stand along page for log in that is
http://norgesavisen.no/dev/logg-inn/

we don't want to show the wordpress default login page   (wp-login.php) , so that is why we created that page. 

everything works fine., but when we enter a wrong password and press login, it took us to  (wp-login.php) page with error message that you entered wrong username or password. 


We want this function should be display on  our /logg-inn/  page.  
Mean when someone enter wrong password, then it must redirected to the  same page  (http://norgesavisen.no/dev/logg-inn/)   not  on  http://norgesavisen.no/dev/wp-login.php  
with error message. 

so please help me in this regard., if that is not possible with S2, then we need to customize the wp-login.php page ourself to achieve this. 

waiting for reply thanks.
