### ISSUE TITLE
Issues With Stripe Payment

### ISSUE THREAD

**Issue by Ashik72** [websharks/s2member-kb#118]
Hi, 
We just put our website live and are excited to start taking payments, however we're seeing something on a particular customer's log that we'd like to help understand what might be going on here. The customer's first transaction was fine, purchasing a subscription from our site (at 8:07:40) but after that it appears he tried purchasing 3 additional shares but there was a cancellation made every time...I'm not sure how he would have done this and the cancellation happens just a few seconds after the purchase is done. Can you help me understand what's going on here please?! Here's a screenshot of what I'm looking at: http://prntscr.com/6d1fkw 

The reply from stripe support is - 

"Thanks for writing in about this, I'm happy to help! I took a look into your account and found two customers associated with that email address[1][2].

If you look at the second one, you can see that he has an active subscription to your plan but this happened after multiple creation and deletion of subscriptions in a row. When I look at all the API logs for that specific customer [3], it definitely looks like you keep asking him for his card details, updating the card, creating a new subscription and deleting the previous one. That customer has also been charged $60 ten times already.

I would advise you to look into your integration to better understand what could be causing all of this. If the charges where not expected, I would also advise you to refund those directly."

and Stripe again lastly with this: " Hey,

When you ask your customer for his card details and then create a customer in Stripe you don't need to ask for his card details again. You can directly charge him or create a new subscription from their saved details. This is why I was a bit confused to see all those calls in the logs.

As for the cancelation, this would come from your integration so you'd need to look into your code to better understand what is causing the first subscription to be canceled each time you create a new subscription.

I also wanted to point out that you might want to look at the `quantity` parameter for the subscription instead of creating separate subscriptions here: https://stripe.com/docs/guides/subscriptions#setting-quantities"

Thanks!

**Comment by jaswsinc** [comment]
We reserve GitHub for discussions regarding the s2Member source code, detailed bug reports, and feature requests. Customer service and technical support for s2Member are handled by our support team. Please open a trouble ticket here. We'll be happy to assist you :-) Please visit: http://wsharks.com/1pYbliq
