### ISSUE TITLE
Mod Security (Odd 403, 503, 500 Errors)

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#153]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

**Markdown File:** http://wsharks.com/18RcPoz
**Published KB Article:** http://s2member.com/kb-article/mod-security-odd-403-503-500-errors/

---

**Comment by rvencu** [comment]
Another cuprit is mod_evasive module that throw 403 if you browse the page/site too fast...

**Comment by darkmattress** [comment]
This article references MediaTemple as a good solution. Unfortunately MediaTemple was purchased by GoDaddy and they are proving to not be nearly as flexible, nor helpful with this issue. May want to remove or replace that reference.
