### ISSUE TITLE
A Quick Queestion On API/Notifications -> Payment Notifications 

### ISSUE THREAD

**Issue by Ashik72** [websharks/s2member-kb#162]
As it says on payment notifications instruction 'a Payment Notification occurs anytime funds are received, no matter what.' - does it also send all specified value with URL?

I've the notification URL like http://domain.com/?s2_payment_notification=yes&user_id=%%user_id%%&item_number=%%item_number%%

My plugin works based on this two variables. It works fine for first time payment but seems on recurring payment, item_number (level:custom_capabilities:fixed term) is not sent. I checked log and isn't seeing that anywhere for recurring but fine with one/first time.

Would someone inform further on this? Seems a bug to me.

Thanks!

**Comment by raamdev** [comment]
@Ashik72 Please post support questions to the [WordPress.org Support Forum](https://wordpress.org/support/plugin/s2member) (for s2Member Framework) or open a [Trouble Ticket](https://www.websharks-inc.com/support/?product=s2member&request_type=trouble_ticket) (s2Member Pro). We reserve this GitHub repo for drafting knowledge base articles. Our other s2Member GitHub repo is reserved for filing bug reports and making feature requests. Thank you! :)
