### ISSUE TITLE
Bug report on API/notifications -> Payment notification

### ISSUE THREAD

**Issue by Ashik72** [websharks/s2member-kb#163]
Please don't close the thread without seeing. I'm just trying to present a bug here. On subscription payment notifications with stripe, s2Member isn't sending replacement codes that are described. On description it says 'a Payment Notification will ALSO be triggered. In other words, a Payment Notification occurs anytime funds are received, no matter what.' and ' Depending on your fee structure, this may include a first Initial Payment that establishes a Subscription. But more importantly, this will be triggered on all future payments that are received for the lifetime of the Subscription.'

So I used this and though worked first time, never did happen on later subscription payments. I can submit log here if you like but please don't tell me to go through native mailing system that takes weeks to reply. I assume this is where I should file a bug.

I've also opened a forum thread here too - https://wordpress.org/support/topic/a-quick-queestion-on-apinotifications-payment-notifications

I'd firmly request you to take a look on either of this.

Thanks!

**Comment by raamdev** [comment]
> I assume this is where I should file a bug.

@Ashik72 No, this is not where you should file a bug. Please file s2Member bugs on the s2Member GitHub Repo: https://github.com/websharks/s2member/issues/

This GitHub repo is reserved for creating the s2Member Knowledge Base (see the [contributing guidelines](https://github.com/websharks/s2member-kb/blob/master/CONTRIBUTING.md)).
