### ISSUE TITLE
Creating a Custom Logout Link

### ISSUE THREAD

**Issue by jaswrks** [websharks/s2member-kb#167]
---
##### KB Article Creation Checklist
- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)
##### Additional TODOs

_Additional TODO list items go here._

---

**Markdown File:** http://wsharks.com/1FHxTuV
**Published KB Article:** http://s2member.com/kb-article/creating-a-custom-logout-link/

---

**Comment by VTMDESIGN** [comment]
Where to put this code and where/how to place a button would be helpful.

**Comment by adaba063** [comment]
the basic link works, but only by redirecting the user to the membership options page,
how to get it to redirect the user, who has selected to "logout", to a page other than the mop?

**Comment by raamdev** [comment]
@adaba063 You simply need to specify a page that is not protected by s2Member. If you redirect the user to a page that requires membership when they logout, then when they logout and get redirected to that page s2Member will see that they're no longer logged in and redirect them to the Membership Options Page.

**Comment by raamdev** [comment]
@VTMDESIGN Apologies for the (very) delayed response. The code should go wherever you want the login link to appear. How and where this occurs really depends on your specific theme, hence the reason the article doesn't get any more specific.
