### ISSUE TITLE
Why am I seeing "Plugin install failed."?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#176]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

- [ ] Consider elaborating more on this topic.

---

[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/176-why-am-i-getting-plugin-install-failed.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/176-why-am-i-getting-plugin-install-failed.md)
:page_with_curl: **Published KB Article:** http://s2member.com/kb-article/why-am-i-getting-plugin-install-failed/

---

**Comment by jaswsinc** [comment]
Great! I'm publishing this, but I'll leave the issue open with a remaining TODO item.

**Comment by raamdev** [comment]
> I'll leave the issue open with a remaining TODO item.

I'd say this can be closed. We don't need to elaborate anymore. If we find people reporting other reasons for seeing this message, we can always reopen this and update the KB Article.

**Comment by jaswsinc** [comment]
Copy that.
