### ISSUE TITLE
Double Opt-In Checkbox Config.

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#179]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/tutorials/2015/179-double-opt-in-checkbox-config.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/tutorials/2015/179-double-opt-in-checkbox-config.md)
:page_with_curl: **Published KB Article:** http://s2member.com/kb-article/double-opt-in-checkbox-config/

---

**Comment by jaswsinc** [comment]
![](http://cdn.websharks-inc.com/s2member/uploads/2014/01/Selection_112.png)

**Comment by renzms** [comment]
@jaswsinc 

Hi Jason, not sure if these are errors, but while reading the article I think it may be missing some words.

On the line: **And, so they are prepared for it come.**

Should it be : **And, so they are prepared for it to come.** , in reference to receiving the confirmation email?

And at the end of the article regarding the options: **No, no not display (or require) the checkbox.**

Should it be:** No, do not display (or require) the checkbox.**?

**Comment by jaswsinc** [comment]
Great catches. Fixed. Thank you! :-)
