### ISSUE TITLE
Why does "Card Start Date or Issue Number" always show on my Pro-Form?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#183]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/183-why-does-card-start-date-or-issue-number-always-show-on-my-pro-form.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/183-why-does-card-start-date-or-issue-number-always-show-on-my-pro-form.md)
:page_with_curl: **Published KB Article:** http://s2member.com/kb-article/why-does-card-start-date-or-issue-number-always-show-on-my-pro-form/

---

**Comment by davidzack** [comment]
This article does not answer the question.  This issue persists even when forms are wrapped as described.

**Comment by raamdev** [comment]
@davidzack Please open a support thread on the community forum (http://forums.wpsharks.com/c/s2member) sharing the exact page content, or at least the exact shortcode(s), that you're using. Please update this GitHub issue with a link to the forum thread once you've opened it.

Also, if you haven't already, please see [Testing in a Clean WordPress Installation](http://s2member.com/kb-article/testing-in-a-clean-wordpress-installation/).
