### ISSUE TITLE
What is the difference between the Membership Options page and the register page?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#19]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

**Markdown File:** http://wsharks.com/1GIiqMB
**Published KB Article:** http://s2member.com/kb-article/what-membership-options/

---

**Comment by cwhyles** [comment]
It would be useful to have this article pinned to the top of the forum, as I was finding the operation of s2members difficult to understand. I thought that perhaps the main registration happened after payment, but it wasn't obvious. Now I see it is just for the free version. A clever solution, though.
