### ISSUE TITLE
re: Can I customize emails that s2Member sends?

### ISSUE THREAD

**Issue by scbwi-admin** [websharks/s2member-kb#198]
Can I customize emails that s2Member sends?
http://s2member.com/kb-article/can-i-customize-emails-that-s2member-sends/
---
Can I include html tags in the email message body?  I'd like to make a link clickable.  Or is there a different way to do that using custom tags?

**Comment by raamdev** [comment]
@scbwi-admin Yes, you can customize the emails s2Member sends (see _s2Member → General Options → Email Configuration_ and the payment gateway-specific emails, e.g. _s2Member → PayPal Options → Signup Confirmation Email_), however HTML Emails are not currently supported by s2Member. I've opened a feature request for these here: https://github.com/websharks/s2member/issues/553

I suggest leaving a comment on that GitHub issue to show your vote for that feature.
