### ISSUE TITLE
What do I need to know about an XML-RPC brute-force attack and s2Member?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#199]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/199-what-do-i-need-to-know-about-an-xml-rpc-brute-force-attack-and-s2member.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/199-what-do-i-need-to-know-about-an-xml-rpc-brute-force-attack-and-s2member.md)
:page_with_curl: **Published KB Article:** http://s2member.com/kb-article/what-do-i-need-to-know-about-an-xml-rpc-brute-force-attack-and-s2member/

---

**Comment by jaswsinc** [comment]
Nice article! This looks ready to publish, right?

Changed:
> snippet of code your sites'

To:
> snippet of code to your sites'

**Comment by raamdev** [comment]
> This looks ready to publish, right?

I made a few more edits and published. :-)
