### ISSUE TITLE
s2Members ProForms Registration Form Problem

### ISSUE THREAD

**Issue by Pointeandshoot** [websharks/s2member-kb#200]
I have installed s2 Pro on a website I am generating for my wife, which sells memberships to access content. I can't seem to figure out how to get the site to go to the Membership Options Page when a user chooses the Register link. Instead, they are taken to the standard WP Registration form. Why is this?

Thanks for the help.

**Comment by jaswsinc** [comment]
We reserve GitHub for discussions regarding the s2Member source code, detailed bug reports, and feature requests. Customer service and technical support for s2Member are handled by our support team. Please open a trouble ticket here. We'll be happy to assist you there :-) Please visit: http://wsharks.com/1pYbliq
