### ISSUE TITLE
How do I protect embedded content?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#201]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/201-how-do-i-protect-embedded-content.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/201-how-do-i-protect-embedded-content.md)
:page_with_curl: **Published KB Article:** http://s2member.com/kb-article/how-do-i-protect-embedded-content/

---

**Comment by raamdev** [comment]
Reopening until I figure out how to solve this issue:

@jaswsinc: Is this a bug? I'm using a YouTube embed code (an `<iframe>` ) in a code block and the iFrame is getting parsed...

![2015-04-28_23-40-37](https://cloud.githubusercontent.com/assets/53005/7384412/92c1e262-ee00-11e4-8d7c-e64dc160444f.png)

**Comment by jaswsinc** [comment]
Yes, that is a bug. Thanks! I am opening a bug report here:
https://github.com/websharks/s2clean/issues/29

**Comment by raamdev** [comment]
@jaswsinc Cool. Thanks!

**Comment by jaswsinc** [comment]
This has been fixed. https://github.com/websharks/s2clean/issues/29

**Comment by raamdev** [comment]
@jaswsinc Thanks! :-)

**Comment by dajaridi** [comment]
You state that the shortcode: [s2If current_user_is(s2member_level1)] is for "The following example only allows users with Level 1 access **or higher** to see the embedded YouTube video:"

Q. Isn't that shortcode ONLY for Level1 one access, not higher? 
And the code for members 1 or higher is:  [s2If current_user_can(access_s2member_level1)] ?

See examples 3 and 2 from the KB article below by Jason C.
Example 2: Full access for any Member with a Level >= 1:
Example 3: Specific content for each different Member Level:
http://s2member.com/kb-article/s2if-simple-shortcode-conditionals/

**Comment by raamdev** [comment]
@dajaridi Yes, you are correct. I've updated the associated KB article. Thank you! :-)
