### ISSUE TITLE
re: Can members register for free?

### ISSUE THREAD

**Issue by yaronelh** [websharks/s2member-kb#211]
Can members register for free?
https://s2member.com/kb-article/can-members-register-for-free/

---

Link to a Relevant article explaining how to create a free membership with a trial period, could help a lot.

**Comment by raamdev** [comment]
@yaronelh Thanks for the KB Article suggestion! :-) I've written that tutorial here:

- [Creating a Free Membership with a Trial Period (Limited-Time Free Membership)](http://s2member.com/kb-article/creating-a-free-membership-with-a-trial-period-limited-time-free-membership/)
