### ISSUE TITLE
Can I automatically add a user to a BuddyPress Group?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#213]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/213-how-can-i-automatically-add-a-user-to-a-buddypress-group.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/213-how-can-i-automatically-add-a-user-to-a-buddypress-group.md)
:page_with_curl: **Published KB Article:** http://s2member.com/kb-article/how-can-i-automatically-add-a-user-to-a-buddypress-group/

---

**Comment by petervangorder** [comment]
I watched the video, by jaswsinc, that convinced me that Custom Capabilities (ccaps) are the way to go and all you need!   I'm sold!    So, how do I achieve Automatically Adding members to a BuddyPress group with ccaps and not levels.    I'm all good with adding code, but I'd need some starter code like that above but for ccaps, not levels.
Thanks!

**Comment by jaswsinc** [comment]
Great idea. I will reopen this so we can update the article soon.

**Comment by petervangorder** [comment]
I presume the next step for many people is...

How do I do this exact same thing (put someone in a BuddyPress Group) when they aren't signing up, but are just purchasing another level?

I presume I execute the same code, but not with this action:
    ws_plugin__s2member_during_configure_user_registration
but with some other action?

That would be useful to know.  Thanks.

**Comment by Mr-Alexander** [comment]
What variables are available within $vars? Would be great to know.

**Comment by jaswsinc** [comment]
@Mr-Alexander writes...

> What variables are available within $vars? Would be great to know.

Thanks for the feedback. The `$vars` are a dump from the current registration context, and it it subject to change at any time. However, among these variables, there is one that will not change, and that is the `$user` variable, which is a `WP_User` object instance; i.e., the most important piece of information needed for a hook such as this one.

_I've updated the article to mention this, and to also mention that you can `print_r($vars);` to see a full list of data for closer inspection if you'd like. http://s2member.com/kb-article/how-can-i-automatically-add-a-user-to-a-buddypress-group/_

**Comment by jaswsinc** [comment]
@petervangorder writes...

> with ccaps and not levels

Thanks for the feedback. I've updated the article to include a second example showing how to do this with CCAPs as the basis for Group addition, instead of Membership Levels. http://s2member.com/kb-article/how-can-i-automatically-add-a-user-to-a-buddypress-group/

---

> How do I do this exact same thing (put someone in a BuddyPress Group) when they aren't signing up, but are just purchasing another level?

The thing to take away from this article is this function exposed by BuddyPress.

```
groups_join_group($bp_group_id, $wp_user_id);
```

With this you can see that it's really just one line needed to add a user to a group. So finding the hook that you need is the challenge that you have. Once you find that, you should be able to just call upon that function and add them to any number of BP Groups that you'd like.
