### ISSUE TITLE
Can one PayPal account handle multiple sites / plugins?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#224]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [](http://s2member.com/kb-article/can-one-paypal-account-handle-multiple-sites/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/224-can-one-paypal-account-handle-multiple-sites.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/224-can-one-paypal-account-handle-multiple-sites.md)

---

**Comment by jaswsinc** [comment]
I see the H3 tag above was missing the article title. This was a bug in the i2KBA converter after recent improvements. I fixed that in the i2KBA converter and updated the H3 tag in this issue.

**Comment by raamdev** [comment]
> I fixed that in the i2KBA converter and updated the H3 tag in this issue.

Thanks!
