### ISSUE TITLE
How can I set Per-Level Unique IP Access Restrictions?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#225]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [How can I set Per-Level Unique IP Access Restrictions?](http://s2member.com/kb-article/how-can-i-set-per-level-unique-ip-access-restrictions/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/225-how-can-i-set-per-level-unique-ip-access-restrictions.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/225-how-can-i-set-per-level-unique-ip-access-restrictions.md)

---

**Comment by jaswsinc** [comment]
@raamdev Looks great! The only suggestion that I have is with the first code sample. It looks great as-is, but you might consider modifying it to alter the existing `$bool` argument value, instead of return a literal boolean value; i.e., potentially overriding an existing filter value that is elsewhere in the chain.

```php
<?php
add_filter('ws_plugin__s2member_disable_specific_ip_restriction', '__s2_disable_certain_ip_restrictions', 10, 2);

function __s2_disable_certain_ip_restrictions ($bool, $vars) { 
    if(username_exists($vars['restriction'])) { 
        $user = new WP_User($vars['restriction']); 

        if($user->has_cap('access_s2member_level4')) 
            $bool = true; 
    }
    return $bool;
}
```

**Comment by raamdev** [comment]
> instead of return a literal boolean value; i.e., potentially overriding an existing filter value that is elsewhere in the cha

Ah, right. Great point. Thanks for catching that. :-)

**Comment by jaswsinc** [comment]
@raamdev One more suggestion.

In this line: `$user = new WP_User($vars['restriction']);`

I suggest changing this to: `$user = new WP_User(0, $vars['restriction']);`

That tells WordPress that is in fact a username that we are looking for. I ran into this issue with usernames that were all numeric. If you pass it in the first argument to the `WP_User()` constructor, WordPress thinks it is an ID instead of a username.

**Comment by raamdev** [comment]
@jaswsinc Ah, thanks for catching that. :-) Updated.

**Comment by RandyKing** [comment]
@raamdev - just what I needed.  On a logistics point, you recommend installing the filter in an S2-specific file.  Will this be overwritten by upgrades to s2Member?  If so, can I just put the filter in my child theme functions.php, or will that create unnecessary overhead?

**Comment by raamdev** [comment]
@RandyKing The article recommends placing the code inside `wp-content/mu-plugins/s2-ip-restrictions.php`, which is **not** inside the s2Member plugin (`wp-content/plugins/s2member/`) but rather inside an [MU-Plugin](http://codex.wordpress.org/Must_Use_Plugins). MU-Plugins don't get overwritten when plugins are updated.

**Comment by RandyKing** [comment]
OH, got it - yes, of course.  Thanks.
