### ISSUE TITLE
What do I need to know about the ccBill phaseout?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#235]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [What do I need to know about the ccBill Phaseout?](http://s2member.com/kb-article/what-do-i-need-to-know-about-the-ccbill-phaseout/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/235-what-do-i-need-to-know-about-the-ccbill-phaseout.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/235-what-do-i-need-to-know-about-the-ccbill-phaseout.md)

---

**Comment by kristineds** [comment]
On this article, it says..

​_“However, future versions of s2Member Pro will be released without ccBill. This will occur in November 2015; i.e., new versions of s2Member Pro will be released without the ccBill integration”_​

I’m using `v160120` and looks like it is still available. Does that mean we still support it? Shouldn’t we update the article as it is confusing to our customers?

**Comment by raamdev** [comment]
@kristineds writes...
> Does that mean we still support it?

No, we no longer provide support for the ccBill or AliPay integration. The article makes this clear on this line: "we will continue to offer assistance with our existing ccBill integration **until November 2015.**" The integration still exists only because we chose not to remove it for the benefit of those who are currently using it, but as of November 2015 we are not maintaining, updating, fixing, or supporting the integration in any way.
