### ISSUE TITLE
What do I need to know about the AliPay phaseout?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#236]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [What do I need to know about the AliPay phaseout?](http://s2member.com/kb-article/what-do-i-need-to-know-about-the-alipay-phaseout/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/236-what-do-i-need-to-know-about-the-alipay-phaseout.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/236-what-do-i-need-to-know-about-the-alipay-phaseout.md)

---

**Comment by jamesatwork** [comment]
For the post : http://s2member.com/kb-article/what-do-i-need-to-know-about-the-alipay-phaseout/
Alipay is the biggest payment gateway in China (maybe also in the whole world).  It has more than 3,5000,0000 users in China.( http://expandedramblings.com/index.php/alipay-statistics/ ) I'm disappointed the retire of Alipay plugin. And you may lost the future in China.
