### ISSUE TITLE
Why does rounding with the [s2Eot /] round_to shortcode attribute not work as expected?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#240]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: Why does rounding with the [s2Eot /] round_to shortcode attribute not work as expected?
categories: questions
tags: 
author: raamdev
github-issue: 
```
---
The `[s2Eot /]` shortcode bases all calculations on the UTC timezone. If you're using the `timezone=""` attribute inside your `[s2Eot /]` shortcode to display EOTs with a specific timezone, keep in mind that rounding calculations will be based on UTC and not the timezone you're using with the `[s2Eot /]` shortcode.

For example, let's say you have an EOT time of `Jul 20th, 2016, 9:48 pm UTC` and on your site you're using the `[s2Eot /]` shortcode as follows:

```wpsc
[s2Eot timezone="EDT" /]
```

That will display the EOT time as `Jul 20th, 2016, 5:48 pm EDT` (4 hours behind UTC).

Now let's say that we add `round_to="tomorrow"` to tell the `[s2Eot /]` shortcode to round up the EOT time to next day. 

```wpsc
[s2Eot timezone="EDT" round_to="tomorrow" /]
```

We'd expect this to mean that the EOT time would now be shown as `Jul 21st`, however since we're showing the EOT time in the `EDT` timezone, it shows the rounded EOT time _4 hours behind UTC_. That means the rounded EOT actually shows as `Jul 20th, 2016, 8:00 pm EDT`.

**Comment by jaswsinc** [comment]
Ah, I hadn't thought of this. Definitely going to lead to confusion.

**Comment by raamdev** [comment]
@jaswsinc Just wanted to double-check that this issue wasn't somehow fixed in the `[s2eot /]` shortcode. Should this KB Article still be published?

**Comment by jaswsinc** [comment]
This was not addressed, no. It's still a potentially confusing behavior.

My feeling is that it's a bug, and that we should update the way rounding is applied in order to avoid this confusion. [This line of code](https://github.com/websharks/s2member/blob/150722/s2member/includes/classes/sc-eots-in.inc.php#L96) should get moved down and applied to [the Date object](https://github.com/websharks/s2member/blob/150722/s2member/includes/classes/sc-eots-in.inc.php#L119) instead. That way rounding is applied after a timezone is set.

**Comment by raamdev** [comment]
Closing this KB Article in favor of fixing this issue in https://github.com/websharks/s2member/issues/671.

**Comment by patdumond** [comment]
I love watching the way you guys go back and forth to figure these things
out. :)
