### ISSUE TITLE
Where is the s2Member data stored in the WordPress database?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#242]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [Where is the s2Member data stored in the WordPress database?](http://s2member.com/kb-article/where-is-the-s2member-data-stored-in-the-wordpress-database/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/242-where-is-the-s2member-data-stored-in-the-wordpress-database.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/242-where-is-the-s2member-data-stored-in-the-wordpress-database.md)

---

**Comment by raamdev** [comment]
@jaswsinc If you could leave some notes here when you get a chance about the various places that s2Member data is stored in the WordPress database, that would help me flesh this article out. :-)

**Comment by jaswsinc** [comment]
Done!

**Comment by raamdev** [comment]
@jaswsinc Awesome! Thanks so much! :-)
