### ISSUE TITLE
How Do I Implement SSL (HTTPS) on My s2Member Site?

### ISSUE THREAD

**Issue by patdumond** [websharks/s2member-kb#249]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Create Markdown file for this Article (remove `draft-finalized` label, add `pending` label)
- [x] Publish KB Article (remove `pending` label, add `published` label; leave this step for the Project Lead)

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [How Do I Implement SSL (HTTPS) on My s2Member Site?](http://s2member.com/kb-article/how-do-i-implement-ssl-https-on-my-s2member-site/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/249-how-do-i-implement-ssl-https-on-my-s2member-site.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/249-how-do-i-implement-ssl-https-on-my-s2member-site.md)

---

**Comment by jaswsinc** [comment]
I love those headings.

Suggested sub-headings for "Setup WordPress for SSL"

- "Forcing SSL in your WordPress Dashboard" https://codex.wordpress.org/Administration_Over_SSL
- "Forcing visitors to log in over SSL" https://codex.wordpress.org/Editing_wp-config.php#Require_SSL_for_Admin_and_Logins

**Comment by patdumond** [comment]
Good ideas, Jason. Probably would have ended up there, but thanks for the
push. Question: How do you feel about external links to commercial
websites. I don't want to push any particular products, but if I say that I
purchased a Comodo SSL certificate, for example, should I link to
Comodo? Thanks in advance.


Made with ♥ by WiseStamp signatures
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MTE0JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzY3MjI5NDExNCIsICJlIjogIjU3NTc3MTUxNzk2MzQ2ODgifQ==>

**Comment by raamdev** [comment]
> How do you feel about external links to commercial
> websites. I don't want to push any particular products, but if I say that I
> purchased a Comodo SSL certificate, for example, should I link to
> Comodo?

I suggest not referring people to Comodo in this scenario. We don't want to refer our users/readers to commercial products unless we've worked closely with them and we're getting some kind of kickback (i.e., commission) from sales referred to them. It's fine to mention that you installed an SSL Certificate from Comodo for the purposes of an article, but I wouldn't link to them.

**Comment by patdumond** [comment]
That was my thinking too, Raam. I just wanted to be sure I was in line with
company policy.



Made with ♥ by WiseStamp signatures
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MTE0JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzY3MjI5NDExNCIsICJlIjogIjU3NTc3MTUxNzk2MzQ2ODgifQ==>

**Comment by patdumond** [comment]
@jaswsinc, @raamdev: Ready for an editorial review. Thanks in advance.

**Comment by raamdev** [comment]
@patdumond This looks great! Here are a few final requested edits:

- [ ] Add introduction paragraph above "Purchase an SSL Certificate". I suggest something that references (and even links to) [Introduction to TLS/SSL and Why You Need It on Your s2Member Site](http://s2member.com/kb-article/introduction-to-tlsssl-and-why-you-need-it-on-your-s2member-site/), a way of picking up where you left off in that article and segueing into this one. Notice how the first paragraph of a KB Article has slightly larger text than the following ones? (Visit the previously mentioned KB article as an example.) I always try to write at least one or two paragraphs before the first heading in the article, as that improves how the article looks visually. Introductions are not _always_ necessary, but in this case I think it makes a lot of sense seeing as how this is continuation of a previous KB article.
- [ ] Add a sentence or two after the "Cipher strength" list item that explains the common Cipher Strength options (and mention higher is better), or simply indicate that the web hosting company will offer you options when purchasing the certificate. "Cipher strength" is the only item in that list that a non-technical person will look at say "huh? what's that? what do I choose?", so I think it makes sense to offer a bit more explanation right after that list.
- [ ] Change "Have the Certificate Installed" header to "Install the SSL Certificate"
- [ ] "Setup WordPress for SSL and HTTPS" -- "Setup" should be "Set up"
- [ ] The following paragraph is confusing, especially from a non-technical perspective, and could use some rewording: "There are excellent reasons for picking a protocol and sticking to it on your website, especially when you require users to log in. The most important to your users is that a session authenticated via HTTPS and a session authenticated via HTTP are treated as two different sessions. Your members will be logged out and asked to log in again when switching protocols."
- [ ] "Setup s2Member for SSL" -- "Setup" should be "Set up"

**Comment by jaswsinc** [comment]
> There are a lot of articles out there that say you need rewrite rules in your .htaccess or telling you to use a plugin to do the redirects for you. This was all probably true when those articles were written. All you have to do, at this point in WordPress history, is set both your WordPress Address (URL) and your Site Address (URL) to begin with https. That's it. That's all.

Setting these URLs so that they have an `https://` protocol will automatically force WordPress into `FORCE_SSL_ADMIN` mode. Referencing [this line of code](https://github.com/WordPress/WordPress/blob/4.3/wp-includes/default-constants.php#L266).

So what you are saying is true. However, the `redirect_canonical()` function in WordPress will only redirect away from an unencrypted `http://` request when it's a `GET` or `HEAD` request. Referencing [this line of code](https://github.com/WordPress/WordPress/blob/4.3/wp-includes/canonical.php#L44-L46).

So for that reason, an `.htaccess` entry to force SSL is still recommended. Without a server config. (or plugin) that forces SSL, WordPress still leaves it possible for HTML markup to be generated with `<form action="http://..." >` and to have that data POSTd over an insecure connection; either by mistake (e.g., a misbehaving theme/plugin) or with malicious intent.

In addition, if there are any files/forms on the site that are outside of WordPress, those would not be covered by `redirect_canonical()` in WordPress, so best to have a server config. that forces SSL in that case also.

## Suggested Apache `.htaccess` Block

_Put this at the very top of your WordPress root `.htaccess` file._

```text
# BEGIN Force SSL
<IfModule rewrite_module>
  RewriteEngine on
  RewriteBase /
  RewriteCond %{HTTPS} !^on$ [NC]
  RewriteCond %{HTTP:X-Forwarded-Proto} !^https$ [NC]
  RewriteRule .* https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
</IfModule>
# END Force SSL
```

---

## Suggested Article Enhancements

- Mention and confirm that that changing your home/site URLs in WordPress does in fact `FORCE_SSL_ADMIN` and reference that line of code in the WordPress codebase to prove it. Note also that `FORCE_SSL_ADMIN` being true, also sets `FORCE_SSL_LOGIN` to true as well; i.e., it makes `FORCE_SSL_LOGIN` [a moot point](https://github.com/WordPress/WordPress/blob/4.3/wp-includes/default-constants.php#L272-L280).

- Suggest that an `.htaccess` entry (as seen above) be used in addition to changing your home/site URLs in WordPress. This provides an added layer of strict enforcement, to help cover some edge cases that are not necessarily covered by WordPress alone at all times.

**Comment by patdumond** [comment]
@jaswsinc, @raamdev: Thanks for the suggestions - everyone needs an editor. I have revised IAW with your suggestions. Ready for another review. Thanks in advance.

**Comment by raamdev** [comment]
@patdumond Here are a few more requested edits:

- [ ] " So for that reason, a `.htaccess.` entry" -- Remove the period (`.`) after `.htaccess`
- [ ] "Referencing this line of code." ← Wherever you have this, it should be replaced with something like "(See [this](#) WordPress source code line.)"
- [ ] "config." ← Any occurrence of this should be changed to "configuration"
- [ ] "However, the redirect_canonical() function in WordPress will only redirect away..." ← that line and everything after it, up until the next heading, should be under its own heading. Those paragraphs don't make any sense tied to the "Setting Your WordPress URLs" heading. Instead, I suggest adding that to a new sub-heading called "Why Isn't That Enough?" to explain why setting the URLs it not enough.
- [ ] "Suggested Apache .htaccess Block" ← This should be its own header and it should not be "suggested"; it should say "Step 2: Updating your .htaccess File"
- [ ] "*Put this at the very top of your WordPress root `.htaccess.' file. Or, if you have an existing block that forces a particular `HTTP_HOST` (some sites do that), then put this right after that block.*" ← There's a problem with the formatting there.
- [ ] After the `.htaccess` rules example, I suggest adding another heading that says "What if I can't edit my .htaccess file?" and then lists and links to a few examples of WP plugins that could be used in place of editing the `.htaccess` file.
- [ ] The following paragraph is confusing, especially from a non-technical perspective, and could use some rewording: "There are excellent reasons for picking a protocol and sticking to it on your website, especially when you require users to log in. The most important to your users is that a session authenticated via HTTPS and a session authenticated via HTTP are treated as two different sessions. Your members will be logged out and asked to log in again when switching protocols."

**Comment by patdumond** [comment]
@raamdev: I've made the changes you recommended above. Thanks so much for the advice.

**Comment by raamdev** [comment]
@patdumond This looks great! Thanks so much for all your work here. :-)

I'm marking this article as **approved as of 2015-09-09** and will let you know of any final edits I make when this gets published.

**Comment by raamdev** [comment]
@patdumond I changed the title and category (see https://github.com/websharks/s2member-kb/commit/b76a5239ee2e3f44da62eae86dc6c0781af461ac) and made several final edits that you may like to review (https://github.com/websharks/s2member-kb/commit/b38006dc64b3cedcc68ebe9a03e41b9ca3049054).

**Comment by raamdev** [comment]
Article published here: http://s2member.com/kb-article/implementing-ssl-https-on-an-s2member-site/

**Comment by Tsiyon-Volunteer** [comment]
This article could be improved by updating it with any/all info about how to do so with the new cPanel built in SSL (HTTPS) certificate or add a link to that information if it is available elsewhere.  Using Google to search for SSL (HTTPS) and S2Member (Pro) brings this article up as the first search engine result.
