### ISSUE TITLE
Can I create membership accounts manually; i.e. after they've paid me?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#25]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

**Markdown File:** http://wsharks.com/1Eqb6Sq
**Published KB Article:** http://s2member.com/kb-article/can-i-create-membership-accounts-manually-i-e-after-theyve-paid-me/

---

**Comment by ghost** [comment]
How do I enter the Last Payment Time manually if a user's paypal info has not come into the db correctly i.e. a recurring payment received, but no Last Payment Time exists...
