### ISSUE TITLE
Can I use Download Restrictions with NGINX?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#250]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [Can I use Download Restrictions with NGINX?](http://s2member.com/kb-article/can-i-use-download-restrictions-with-nginx/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/250-can-i-use-download-restrictions-with-nginx.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/250-can-i-use-download-restrictions-with-nginx.md)

---

**Comment by jaswsinc** [comment]
> relies almost exclusively on the PHP

on ~~the~~ PHP

---

> While s2Member adds an .htaccess file to that directory to prevent direct, public access to files in that directory, NGINX does not support .htaccess files.

**Suggest:** _s2Member adds an `.htaccess` file to that directory to prevent public access. However, NGINX does not support `.htaccess` files._

---

> to tell the [s2Steam /] shortcode not

`[s2Stream /]`

---

> ## Advanced Mod-Rewrite Linkage

I'd move that heading just above the section that discusses `[s2Stream /]` so that reading about the `rewrite="no"` attribute will make a little more sense--assuming it's a tech-savvy person.

**Comment by jaswsinc** [comment]
> [s2If /]

I think that should be `[s2File /]`

**Comment by raamdev** [comment]
> I think that should be [s2File /]

Ha, thanks. That's what I get for writing about `[s2If /]` in another GitHub issue while in the middle of writing this one. ;)

I applied your other edits too--thanks for those.

**Comment by jaswsinc** [comment]
Awesome! That looks great to me.
