### ISSUE TITLE
Can I add the New EOT Shortcode to the PRO Login Widget?

### ISSUE THREAD

**Issue by renzms** [websharks/s2member-kb#253]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

## Published @ s2Member.com: http://s2member.com/kb-article/can-the-eot-time-be-added-to-the-pro-login-widget/

[View Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/253-can-the-eot-time-be-added-to-the-pro-login-widget.md)

**Comment by jaswsinc** [comment]
Hey! :-) Great to see you working on KBAs like this. Thank you!

---

> Can I Add The New EOT Shortcode To PRO Login Widget?

Questions can be written without title case.
e.g., **Can I add the new EOT Shortcode to the Pro Login Widget?**

Note that:

- I am using regular sentence-case; e.g., **Can I add the new...**
- However, I always capitalize feature titles like: **Pro Login Widget** and **EOT Shortcode**

---

> Yes, you should be able to add it using PHP code

I realize this is just a draft, but try to refrain from using words like "should" or "might" or "maybe". You want the article to present an official answer to the question. Words like should or maybe suggest that it _might_ be the right answer, and that's not people want to see in the official KB for the software.

_Remember you can always ask one of us if you're unsure._

---

The Pro Login Widget supports arbitrary XHTML/PHP and even shortcodes. So I don't think it's absolutely necessary to install something like ezPHP to answer this question. I think mentioning ezPHP is great, but we should also mention that the Pro Login Widget has these fields that you can use. In fact, you could even insert the `[s2Eot /]` shortcode right into these fields.

![2015-08-12_01-17-04](https://cloud.githubusercontent.com/assets/1563559/9220789/6fc4a892-4091-11e5-8a6a-7c3468ee7f1b.png)

**Comment by raamdev** [comment]
> In fact, you could even insert the `[s2Eot /]` shortcode right into these fields.

@jaswsinc Interesting. I was not even aware of that. :-) Should _any_ WordPress shortcode work there? If so, maybe we can change those field titles to "Additional XHTML/PHP Code or Shortcode?"

**Comment by renzms** [comment]
@jaswsinc 

Thanks for the feedback and guidance! I'll take note of the changes and edit the draft. I didn't know you could just use the short code straight into the widget fields, so thanks for that too. I'll make the article explain that shortcode can be used to show EOT and also the method for using PHP as an additional method to show EOT. That should cover all bases.

**Comment by renzms** [comment]
> "Additional XHTML/PHP Code or Shortcode?"

@jaswsinc and @raamdev , I agree with Raam, maybe it should include the words "and Shortcodes". But like he asked, are there any limitations on the shortcodes that should work, or is it only applicable to certain s2member shortcodes?

**Comment by jaswsinc** [comment]
> Should any WordPress shortcode work there?

Yes. Any shortcode should work here. I'm opening an issue here. I agree.
https://github.com/websharks/s2member/issues/691

**Comment by jaswsinc** [comment]
@renzms Latest improvements look good! :-)
