### ISSUE TITLE
re: Will s2Member protect content excerpts, feeds, searches, archive views?

### ISSUE THREAD

**Issue by patdumond** [websharks/s2member-kb#258]
Will s2Member protect content excerpts, feeds, searches, archive views?
http://s2member.com/kb-article/will-s2member-protect-snippets-excerpts-feeds-searches-too/

---

We should add the dashboard location for this feature: **WordPress Dashboard →s2Member®(Pro) → Restriction Options → Alternative Views Protection**

**Comment by jaswsinc** [comment]
Done. Thanks!
