### ISSUE TITLE
re: Does s2Member integrate w/ Stripe? Bitcoin?

### ISSUE THREAD

**Issue by fabrice88** [websharks/s2member-kb#260]
Does s2Member integrate w/ Stripe? Bitcoin?
https://s2member.com/kb-article/does-s2member-integrate-w-stripe-bitcoin/

---

Hello,

The Stripe pro form is not translate in French, however in stripe plateform it is.
And it take text and picture from local rather of Stripe 

Thx Fabrice

**Comment by raamdev** [comment]
@fabrice88 We reserve this GitHub repo for s2Member KB Articles (see [guidelines for contributing](https://github.com/websharks/s2member-kb/blob/master/CONTRIBUTING.md)). If you have a bug to report, please open your bug report here: http://github.com/websharks/s2member/issues/
