### ISSUE TITLE
How do I send an email when the membership level is changed?

### ISSUE THREAD

**Issue by kristineds** [websharks/s2member-kb#263]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [How do I send an email when the membership level is changed?](http://s2member.com/kb-article/how-do-i-send-an-email-when-the-membership-level-is-changed/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/263-how-do-i-send-an-email-when-the-membership-level-is-changed.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/263-how-do-i-send-an-email-when-the-membership-level-is-changed.md)

---

**Comment by jaswsinc** [comment]
@kristineds Great! You can enhance this article by building an example call to `wp_mail()` (https://codex.wordpress.org/Function_Reference/wp_mail) that sends a user an email message.

Something like:

```php
$user = new WP_User($user_id);

$subject = 'Test Email Subject';
$message = 'Testing one, two, three.';

wp_mail($user->user_email, $subject, $message);
```

Referencing: https://codex.wordpress.org/Class_Reference/WP_User

**Comment by raamdev** [comment]
@kristineds Nice first draft! Here's some feedback:

---

- [ ] "However, you can track it in WordPress by" → "However, you can do this by"
- [ ] "or hacking s2Member with Hooks and Filters" → "or customizing s2Member with Hooks and Filters" 
     
     I like to avoid using the word 'hacking' as it often scares people away when they think that it might break something.

- [ ] `s2-hacks.php` → `s2-role-change-handler.php` 

     In the past we've used `s2-hacks.php` as a common filename to place these sorts of customizations inside, but Jason and I agreed some time back that it makes sense to give these unique filenames that are relevant to what the code is doing; also getting rid of 'hacks' in the filename helps people feel a bit better about implementing such customizations.

**Comment by kristineds** [comment]
@jaswsinc @raamdev Thank you for the feedback! I'll start working on this. :)

**Comment by kristineds** [comment]
@jaswsinc @raamdev Updated the article to include both your feedback. Could you please check if I added the `wp_mail()` code in the right place? :)

**Comment by raamdev** [comment]
> Could you please check if I added the wp_mail() code in the right place? :)

Looks good to me, but I suggest trying this out on your test site to test it. :-) Create a test user, modify the role, then see if you get the email. 

Also, I recommend adding the language marker to the starting fence of the code block like this:

```
```php
```

That will enable syntax highlighting and make the code easier to read. :-)

**Comment by kristineds** [comment]
@raamdev wrote:
> Create a test user, modify the role, then see if you get the email.

I didn't get any email. :( What am I missing?

**Comment by jaswsinc** [comment]
@kristineds Try this modified version that I tweaked to work with admin role changes.

```php
<?php
add_action('init', 's2_role_change_event_handler::init', 1);

class s2_role_change_event_handler
{
    public static $user_id;
    public static $user_old_role;

    public static function init()
    {
        global $pagenow;

        if (!is_admin()) {
            return; // Not applicable.
        }
        if ($pagenow !== 'user-edit.php') {
            return; // Not applicable.
        }
        if (empty($_REQUEST['user_id'])) {
            return; // Not applicable.
        }
        if (!current_user_can('edit_users')) {
            return; // Not applicable.
        }
        $user = new WP_User((int) $_REQUEST['user_id']);

        static::$user_id       = $user->ID;
        static::$user_old_role = reset($user->roles);

        add_action('set_user_role', 's2_role_change_event_handler::event', 10, 2);
    }

    public static function event($user_id, $new_role)
    {
        if ($user_id === static::$user_id && $new_role !== static::$user_old_role) {
            if (($user = new WP_User($user_id)) && $user->exists()) {
                $subject = 'User Role Update';
                $message = 'Hello! This is to notify you that your User Role has been changed.';
                wp_mail($user->user_email, $subject, $message);
            }
        }
    }
}
```

**Comment by kristineds** [comment]
@jaswsinc Thank you! It works now. :) I added `$headers` and updated the `$message` to include the `$new_role`
@raamdev I changed the title so it's specific to manually changed user roles, or is it not necessary? Also added some more info for the description. Waiting for your feedback.

**Comment by raamdev** [comment]
@kristineds Looking great! Here's some more feedback:

- [ ] I would change the title to "How do I send an email when the membership level is changed?" (don't forget to update this GitHub issue title _and_ the title in the YAML markup).
- [ ] The introduction paragraph is a bit short and feels incomplete. I suggest adding a sentence or two that describes a common scenario where a site owner needs to manually change the user role (e.g., [manually approving user accounts](http://s2member.com/kb-article/how-can-i-manually-approve-user-accounts/) ← that would be a good article to link to in the introduction too) and then explains that this article will detail how to automatically send an email to the user whenever their s2Member Level is changed from the WordPress Dashboard. 
- [ ] I would explain somewhere that this article does not apply to the the Billing Modification Form, which sends its own email when the user modifies their own account using a Billing Modification Form (see **s2Member → [Payment Gateway] Options → Modification Confirmation Email (Standard/Pro Form)**).

**Comment by kristineds** [comment]
@raamdev Updated the article with your feedback. :)  Could you please review it when you get a chance? Thank you!

**Comment by raamdev** [comment]
@kristineds Awesome! This almost looks ready to go! :-) Here's a bit more feedback:

- [ ] "See: **s2Member → [Payment Gateway] Options → Modification Confirmation Email (Standard/Pro Form)**." ← Please add "WordPress Dashboard → " to the beginning of that menu path; when you add "Dashboard" or "WordPress Dashboard" to the beginning of the menu path it will styled differently on the website so that it's obvious it's a menu path. (If you've seen the blue-styled menu paths in KB Articles, that's where this comes from--but the menu path must start with one of those keywords for the preprocessor to pick it up and style it properly.)
- [ ] "implementing a MU plugin" ← I would change that to "creating an MU-Plugin"
- [ ] "sending an email using the wp_mail() function. WordPress sends email using wp_mail() similar to PHP’s mail()" ← I noticed you linked `wp_mail()` twice here--I suggest only linking to it once, otherwise it seems like they're two different links.

_Note: Please don't check off those checkboxes above--those are for me to check off once I've confirmed you've made the requested edits. You can use the checkboxes while you're working if you like, as long as you uncheck them when you're done. :-)_

**Comment by kristineds** [comment]
@raamdev All good! Thanks for the feedback. If I missed anything, let me know. :)

**Comment by raamdev** [comment]
@kristineds Marking this as **approved as of 2015-10-28**. Nice work!

I made a few edits that you may be interested in reviewing; see https://github.com/websharks/s2member-kb/commit/6e05c3ebc98acd91ba2b46db43f423f53e3762b4

**Comment by kristineds** [comment]
:+1:

**Comment by jaswsinc** [comment]
:+1:
