### ISSUE TITLE
How do I offer an installment plan?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#265]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [How do I offer an installment plan?](http://s2member.com/kb-article/how-do-i-offer-an-installment-plan/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/265-how-do-i-offer-an-installment-plan.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/265-how-do-i-offer-an-installment-plan.md)

---

**Comment by raamdev** [comment]
@jaswsinc Review please, when you get a chance?

Also, is it possible to disable the EOT System _only_ for subscriptions that are using an installment plan (with a filter), or is it all-or-nothing (enable the EOT System and lose access at the end of an installment, or disable the EOT System altogether to prevent loss of access but also lose the ability to automatically expire access)?

**Comment by jaswsinc** [comment]
> Review please (for accuracy), when you get a chance?

Looks great!

> or is it all-or-nothing

Yes, it is currently an all-or-nothing type of thing.

**Comment by raamdev** [comment]
@jaswsinc Thanks! :-)

**Comment by raamdev** [comment]
@raamdev writes...
> How difficult would that be to do via a filter? For example, what if the site owner was using a Custom Capability called `trial` to identify subscribers who were on a trial period (and therefore SHOULD be demoted via the EOT if they don't upgrade). Is this like a one-liner, "if has Custom Capability `trial`, proceed with the EOT transition, else skip it", or is it more complicated than that?

@jaswsinc writes...
> It's slightly more complex than a single filter at the moment, because while most EOTs take place via WP Cron through a single routine, an EOT can also take place (in code) through an IPN handler. I'm not seeing an easy way to add a filter currently supported by s2Member that would accomplish this.

**Comment by gui11aumeCode** [comment]
Hi Raamdev,
I was reading your article https://s2member.com/kb-article/how-do-i-offer-an-installment-plan/ and I run some test for a recurring payment using rrt tag. I thought it would be great to have an example in the article.

For instance I have create this button:
[s2Member-Pro-Stripe-Form level=“2” ccaps="" desc=“1 Days @ $1.39 / then $0.51 / Daily (recurring charge, for 1 days)” cc=“EUR” custom=“” ta=“1.39” tp=“1” tt=“D” ra=“0.51” rp=“1” rt=“D” rr=“1” rrt=“1” coupon="" accept_coupons=“0” default_country_code=“US” captcha=“0” /]

Everything works fine but unfortunately the recurring payment never stops, it is like the rrt tag changes nothing. I am not sure if I missed something or if this feature is not available anymore. 
Also, your article bring me here but I am not sure if this is the right place to ask and I am sorry if it is not.

Thank you,
Guillaume

**Comment by raamdev** [comment]
@gui11aumeCode I'm no longer involved with this project. @clavaque has taken over and questions should be addressed to him now. 😄

**Comment by gui11aumeCode** [comment]
Ok Raamdev, thank you for your answer I'll contact him.
