### ISSUE TITLE
What metadata does s2Member pass to Stripe?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#266]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [What metadata does s2Member pass to Stripe?](http://s2member.com/kb-article/what-metadata-does-s2member-pass-to-stripe/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/266-what-metadata-does-s2member-pass-to-stripe.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/266-what-metadata-does-s2member-pass-to-stripe.md)

---

**Comment by raamdev** [comment]
@jaswsinc Nice article! Here's some feedback:

A bit more context in the article would help. For example, at the end in the Dev Notes you say this:

> or instance, in PHP you would `json_decode($metadata->tax_info)` to gain access to the object properties for the tax information.

But there's no example or hint as to how or where a developer would gain access to `$metadata`. Would that be via a filter? A quick PHP example below the Dev Notes section would help a lot.

**Comment by jaswsinc** [comment]
Thank you. I'm working with Quaderno on this also, so this article will most likely evolve over the next few days and/or weeks. I'll be sure to elaborate on that example whenever I add details to this.

**Comment by jaswsinc** [comment]
I added some additional details at the top to helpl explain the context of this article:
 http://s2member.com/kb-article/what-metadata-does-s2member-pass-to-stripe/
