### ISSUE TITLE
How do I generate an s2Member PayPal Button link?

### ISSUE THREAD

**Issue by patdumond** [websharks/s2member-kb#268]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue draft and either questions or tutorials
- [x] Add required YAML configuration
- [x] Add Tags for this KB Article to the YAML config (see YAML Keys (Explained))
- [x] Edit and finalize draft for publishing (remove draft label, add draft-finalized label)
- [x] Create Markdown file for this Article (remove draft-finalized label, add pending label)
- [x] Publish KB Article (remove pending label, add published label; leave this step for the Project Lead)

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [How do I generate an s2Member PayPal Button link?](http://s2member.com/kb-article/how-do-i-generate-an-s2member-paypal-button-link/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/268-how-do-i-generate-an-s2member-paypal-button-link.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/268-how-do-i-generate-an-s2member-paypal-button-link.md)

---

**Comment by patdumond** [comment]
@raamdev, @jaswsinc: KBA for review. Reference Zendesk ticket: [https://websharks.zendesk.com/agent/tickets/8743](https://websharks.zendesk.com/agent/tickets/8743)

**Comment by raamdev** [comment]
@patdumond Here's some feedback:

The YAML block at the top is missing the YAML marker. See the example below (notice the `yaml` part at the start of the fenced codeblock).

_Note that you'll need to remove the `\` from the fenced code block around the YAML config in the example below; the `\` was necessary below to prevent GitHub from parsing that fenced code block._

```
``\`yaml
title:
categories:
tags:
author: 
github-issue:
``\`
```

> You can use a link instead of a button for PayPal using the output= attribute of s2Member's PayPal button shortcode.

I would add a bit more to the introduction and explain _how_ the link can be used (i.e., in a standard `<a></a>` anchor element), and _why_ you might want to generate a link: Useful when creating custom "buy now" or "purchase" buttons in a features table, for example.

> Substitute `output="url"` for `output="button"` in the shortcode.

I think you have that backwards. :-)

**Comment by patdumond** [comment]
@raamdev wrote:

>Substitute output="url" for output="button" in the shortcode.
I think you have that backwards. :-)

No, I don't, but I guess I need to say it another way. ;)

**Comment by patdumond** [comment]
@raamdev wrote:

>The YAML block at the top is missing the YAML marker. See the example below (notice the yaml part at the start of the fenced codeblock).

Hmmm... I don't know how that happened. Fixed it.

**Comment by raamdev** [comment]
@patdumond The opening fenced code block for the YAML still looks wrong:

![2015-10-07_15-46-33](https://cloud.githubusercontent.com/assets/53005/10349074/a8b2e182-6d0a-11e5-877d-08228f4a6c95.png)

The `yaml` should be at the very end of the fenced code block (i.e., three back-ticks followed by `yaml`).

**Comment by raamdev** [comment]
Also, this shouldn't be there (the title of the GitHub issue and the `title:` attribute in the YAML markup is the title of the article; there should not be an additional H1 at the top):

![2015-10-07_15-48-13](https://cloud.githubusercontent.com/assets/53005/10349126/ee72ee10-6d0a-11e5-8349-da27e628d3e0.png)

**Comment by jaswsinc** [comment]
Nice article :-)

> Substitute output="url" for output="button" in the shortcode.
> No, I don't, but I guess I need to say it another way. ;)

ah, tricky! I read this wrong the first time I saw it. It looks right to me now!

Maybe it could be written as:
Change `output="button"` to `output="url"`

**Comment by raamdev** [comment]
> ah, tricky! I read this wrong the first time I saw it. It looks right to me now!

Oh, I see now. That's really confusing IMO. :-)

This would be less likely to cause confusion: 

"Change `output="button"` to `output="url"` in the shortcode."

**Comment by patdumond** [comment]
@raamdev wrote:

>Oh, I see now. That's really confusing IMO. :-)

>This would be less likely to cause confusion:

>"Change output="button" to output="url" in the shortcode."

I guess "substitute this for that" isn't as self-explanatory as I thought. ;)  Changes made. I also expanded the introduction a bit.

**Comment by raamdev** [comment]
@patdumond Cool! Looks good to me. The only thing left is the YAML is still broken as I described above. :-)

**Comment by patdumond** [comment]
@raamdev: Fixed it. I thought I'd done that before, but must have copied it back over or something.

**Comment by raamdev** [comment]
@patdumond Thank you!

I'm marking this **approved as of 2015-10-16**.

**Comment by kristineds** [comment]
A customer suggested...
> maybe that information could be made a little more obvious than hidden in the KB! 

Another way of asking "How do I generate an s2Member PayPal Button link" is "Can A Shortcode Become A URL?"
