### ISSUE TITLE
How do I display protected PDFs with the PDF Viewer plugin?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#274]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [How do I display protected PDFs with the PDF Viewer plugin?](http://s2member.com/kb-article/how-do-i-display-protected-pdfs-with-the-pdf-viewer-plugin/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/274-how-do-i-display-protected-pdfs-with-the-pdf-viewer-plugin.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/274-how-do-i-display-protected-pdfs-with-the-pdf-viewer-plugin.md)

---

**Comment by jaswsinc** [comment]
Cool! I noticed a couple of minor problems in this article.

- The list items (`1`, `2`, `3`) got mangled on the s2Member.com side for some reason.
- `s2member-file-inline-no` is the same as `inline="no"` and not `inline="yes"`.

My feeling is that the PDF Viewer _should_ receive the file as a downloadable attachment (not inline, which worked fine in my test), because the PDF Viewer is downloading the file and then displaying it in the browser. However, I didn't test this the other way around, so it's possible that the PDF Viewer will work either way.

**Comment by raamdev** [comment]
@jaswsinc Thanks! Fixed. https://github.com/websharks/s2member-kb/commit/509fb506f9f4b9862e86b5f6e710a5ea2939a287

**Comment by patdumond** [comment]
@raamdev : I see you published this already, but I have a question. Is this specific to the plug-in you mentioned? I don't have any trouble with PDF viewing of protected files on my websites. Thanks in advance.

**Comment by raamdev** [comment]
@patdumond Yes, this is specific to the PDF Viewer plugin. If you're just downloading or viewing protected PDFs in your browser (using the browser's PDF plugin), that will work fine with all the methods of linking to s2Member-protected files.
