### ISSUE TITLE
s2Member + BuddyPress + bbPress?

### ISSUE THREAD

**Issue by tamara59** [websharks/s2member-kb#275]
I'm having problems getting the forums to show up properly using the theme that was recommended on the S2Member site. The theme is InFocus by MySiteMyWay. It looks like the recommendation to use that theme is pretty old.

Any suggestions for themes that play nice with S2+BuddyPress+bbPress?

Much appreciated!

Tammy

**Comment by jaswsinc** [comment]
We reserve GitHub for discussions regarding the s2Member source code, detailed bug reports, and feature requests. Customer service and technical support for s2Member are handled by our support team. Please open a trouble ticket here. We'll be happy to assist you there :-) Please visit: http://wsharks.com/1pYbliq
