### ISSUE TITLE
Where is your Stipe?  Video isn't same as program

### ISSUE THREAD

**Issue by needmoreinfoarh** [websharks/s2member-kb#276]
It's good you have Videos!  ...esp for those of us who would rather just have the answer handy.  Thank you.

However, it befuddles me why people's videos rarely look like/match their own programs.  

Like this site...I just want a membership site to immediately redirect new members AFTER Registration to the Choices of Membership to choose.  Why does this seem foreign and not addressed?...without spending another 100 hours online, youtube, etc?  

That's like me selling a course on Taxes and when they come to the meeting I'm showing Basket Weaving.

**Comment by jaswsinc** [comment]
We reserve GitHub for discussions regarding the s2Member source code, detailed bug reports, and feature requests. Customer service and technical support for s2Member are handled by our support team. Please open a trouble ticket here. We'll be happy to assist you there :-) Please visit: http://wsharks.com/1pYbliq
