### ISSUE TITLE
Integrating other plugins with s2Member

### ISSUE THREAD

**Issue by KTS915** [websharks/s2member-kb#277]
Here's a first draft of a suggested KB article on integrating other plugins with s2Member. Please feel free to edit as you see fit, including adding other plugins.

I am amazed to find that Github doesn't support the open-source .odt format, so I've had to convert this to .docx, which has messed up some of the formatting. Let me know if you prefer a different format!

[Integrating plugins with s2Member.docx](https://github.com/websharks/s2member-kb/files/37350/Integrating.plugins.with.s2Member.docx)

**Comment by KTS915** [comment]
Here it is in Markdown:

**Which other plugins integrate well with s2Member?**

s2Member has been designed to make optimum use of core WordPress functions. It does not add its own tables to your site's database, but instead uses the regular WordPress tables.

This means that s2Member's functionality can easily be extended by using other plugins, even if they have not been designed specifically with s2Member in mind. Below is a list of plugins that integrate particularly well with s2Member, organized according to the function that they provide.

Please note that this list is _not_ exhaustive. It simply lists those plugins that we have either used ourselves or that have been reported by s2Member users as integrating well with s2Member.

**Caching**

[WP Super Cache](https://wordpress.org/plugins/wp-super-cache/)

[W3 Total Cache](https://wordpress.org/plugins/w3-total-cache/) (provided that object caching is not enabled)

[Zen Cache](https://wordpress.org/plugins/zencache/)

[Zen Cache Pro](https://zencache.com/) (paid plugin)

We are the developers of Zen Cache and Zen Cache Pro, so these can always be guaranteed to work with s2Member. Zen Cache Pro offers the significant advantage that it makes it possible to cache content for logged-in members. It also offers the ability to compress (minify) CSS and javascript files, which will make your site go even faster.

**Capability Management**

[Capability Manager Enhanced](https://wordpress.org/plugins/capability-manager-enhanced/)

[Members](https://wordpress.org/plugins/members/)

Both these plugins enable you to have much finer-grained control over which capabilities are assigned to each user role (including s2Member levels). This enables you, for example, to allow those with s2Member Level 1 to have access to content that would otherwise be restricted to those at s2Member Level 4 and above.

Perhaps more importantly, these plugins also enable you to change the default hierarchical structure of s2Member levels. You could therefore use either of them to prevent users at s2Member Level 2 and s2Member Level 3 from being able to access content designated for those at s2Member Level 1.

**Changing Text Created by s2Member**

[Say What?](https://wordpress.org/plugins/say-what/)

s2Member and s2Member Pro provide a variety of forms and buttons for use on your site. You might, however, prefer to use different words or phrases (whether in English or another language) instead of the default s2Member text. This plugin (which, when activated, will appear in your Tools menu under Text Changes) enables you to do so easily by simply filling in four boxes for each phrase you wish to change.

Those boxes are as follows:

1. Original string: type in the current text
2. Text Domain: type "s2member" (without the quotes)
3. Text Context: type "s2member-front" (without the quotes)
4. Replacement String: type in your desired text

**Comment Subscriptions**

[Comment Mail](https://wordpress.org/plugins/comment-mail/)

[Comment Mail Pro](http://comment-mail.com/) (paid plugin)

We are the developers of both these plugins. They allow commenters to sign up for email notifications whenever they leave a comment on your site. Or, they can also subscribe without commenting — the choice is theirs.

This is a fantastic way to engage visitors — giving them the details they want, when (and how) they want them!

**Counting Hits on Posts and Pages**

[Post Views Counter](https://wordpress.org/plugins/post-views-counter/)

This plugin provides a means of displaying how many times a post or page has been viewed. There are options for displaying in the admin pages and/or on the front end, and it is possible to exclude visits by those with specific roles (including s2Member roles) from being counted.

**Groups Management**

[KC Groups Management](http://krumch.com/2013/07/09/kc-groups-management/#.Vklev3q350w) (paid plugin)

This enables one user to purchase a bundle of s2Member memberships that s/he can then control. This is very useful if, for example, you have a corporate client who wishes to enable access for a number of employees.

**Identifying Post and Page IDs**

[Reveal IDs](https://wordpress.org/plugins/reveal-ids-for-wp-admin-25/)

[WP Show Ids](https://wordpress.org/plugins/wp-show-ids/)

Sometimes, when using s2Member, you might wish to protect a specific post or page and need to obtain its ID. Both these plugins add the ID number of each post and page to the lists of posts and pages in the WordPress admin pages.

**Login and Registration**

[Clean Login](https://wordpress.org/plugins/clean-login/)

[Theme My Login](https://wordpress.org/plugins/theme-my-login/)

Both these plugins enable you to style the login and registration pages and yet maintain compatibility with s2Member. However, they do so in different ways. Theme My Login provides a means of styling the default WordPress login and registration pages. Clean Login, on the other hand provides a means of creating new login and registration pages using regular WordPress pages.

Note that s2Member Pro also provides a widget that can be placed in any sidebar so as to enable a member to login on any post or page where that widget appears.

**MailChimp Integration**

[KC S2M+MC](https://wordpress.org/plugins/kc-s2mmc/)

s2Member already enables basic integration capabilities with MailChimp. This plugin takes that integration much deeper, so that users can be added either from s2Member or from MailChimp, and they will be synced across to the other application.

**Menus**

[Nav Menu Roles](https://wordpress.org/plugins/nav-menu-roles/)

[Privilege Menu](https://wordpress.org/plugins/privilege-menu/)

If you enable all Alternative View Protections in s2Member (or check the Nav Menus box option) then s2Member will ensure that menu items will reflect the user role of the current user. In other words, someone at s2Member Level 1 will see on the menu only those items that are accessible to someone with that user level.

These two plugins offer more fine-grained control. You might, for example, wish someone with s2Member Level 1 access to be able to see a menu item that is accessible only for someone at s2Member Level 2 so that this can act as a "teaser," encouraging them to purchase an upgrade.

**PHP in Posts and Pages**

[ez](https://wordpress.org/plugins/ezphp/) [PHP](https://wordpress.org/plugins/ezphp/)

There are other plugins that also offer the capability to add PHP code to posts and pages. However, we are the developers of the ezPHP plugin, and recommend it because, besides the regular PHP syntax, it provides an alternative way of inserting PHP that uses shortcodes. This makes it possible to use on the visual editor of a post or page, as well as on the text editor.

**Protected Downloads Management and Tracking**

[**s2**](https://wordpress.org/plugins/s2member-secure-file-browser/) [**M**](https://wordpress.org/plugins/s2member-secure-file-browser/) [**ember Secure File Browser**](https://wordpress.org/plugins/s2member-secure-file-browser/)

This plugin provides fine-grained control of your protected file downloads (including downloads served inline). It also enables you to track how many times a file has been downloaded, and by whom.

**Spam Prevention**

[Ban Hammer](https://wordpress.org/plugins/ban-hammer/)

[Anti-Spam by CleanTalk](https://wordpress.org/plugins/cleantalk-spam-protect/)

[WP-SpamShield Anti-Spam](https://wordpress.org/plugins/wp-spamshield/)

So long as you are using the default WordPress registration form, Ban Hammer provides a way of preventing registrations from users with email domains that you can specify.

The other two plugins provide more general spam protection on login and registration forms, including forms generated by s2Member and s2Member Pro.

**User Data: Listing, Searching, and Sorting**

[AMR Users](https://wordpress.org/plugins/amr-users/)

[AMR](https://wpusersplugin.com/downloads/amr-users-plus-s2-member/) [U](https://wpusersplugin.com/downloads/amr-users-plus-s2-member/) [sers](https://wpusersplugin.com/downloads/amr-users-plus-s2-member/) [P](https://wpusersplugin.com/downloads/amr-users-plus-s2-member/) [lus s2](https://wpusersplugin.com/downloads/amr-users-plus-s2-member/) [M](https://wpusersplugin.com/downloads/amr-users-plus-s2-member/) [ember](https://wpusersplugin.com/downloads/amr-users-plus-s2-member/) (paid plugin)

s2Member Pro provides an [s2Member-List /] shortcode that makes it possible for site owners to build a list of their members in a variety of ways. The shortcode might be used to present a list of your highest ranking members, or simply to provide other members with a way to search for each other. There are a lot of use cases for this, and the shortcode is quite flexible. More details are [here](https://s2member.com/kb-article/s2member-list-shortcode-documentation/).

If, however, you have some other use case that this shortcode does not cater for, these two plugins provide other ways to build lists of your members.

**Widgets**

[Display Widgets](https://wordpress.org/plugins/display-widgets/)

This plugin adds a series of options to each active widget that enable you to control not only the posts, pages, categories, etc. on which the widget appears, but also which user roles (including s2Member user roles) will be able to see it.

**Comment by patdumond** [comment]
@KTS915 - @raamdev asked me to take a look at this because I just suggested *Nav Menu Roles* to the team for support purposes. I haven't used *Theme My Login* but we have an [open issue](https://github.com/websharks/s2member/issues/712) describing some problems with using it with s2Member. Those can be overcome if you understand how each plugin works, but it can be a problem for some users.

I have been using *Gravity Forms* successfully with s2Member for user registration and login too. I haven't tried integrating it for payment forms however. 

If you'd like me to provide any more information on either *Gravity Forms* or *Theme My Login* use, I'd be happy to do so. (Ticket flow is very heavy right now though so it might not be tomorrow. ;))

**Comment by jaswsinc** [comment]
@KTS915 Outstanding article. Great structure. Thank you so much! 
I can't wait to see this make its way through Raam's review process and over to http://s2member.com/kb/

**Comment by KTS915** [comment]
@patdumond,

Yes, Nav Menu Roles is a very good plugin. (And Privilege Menu is equally good.)

I am happy to leave out Theme My Login. I personally don't like the plugin anyway. (I use Clean Login.) I included it only because I know a lot of people use it. But if it's causing problems, let's omit it.

I have never used Gravity Forms, and don't ever plan to. Feel free to add an entry on that plugin. Indeed, I assume we'll be adding to (and, occasionally, subtracting from) this list from time to time anyway. I certainly don't envisage its being pickled in aspic.

**Comment by KTS915** [comment]
Now that I know that I need to paste in any document in Markdown, that should make things much easier, as I can go back to my favorite word-processor, LyX, and just export to Markdown. So here's an updated version, with Theme Login removed, and Sidebar Login and Admin Bar Disabler added. 

Which other plugins integrate well with s2Member? {#which-other-plugins-integrate-well-with-s2member .unnumbered}
=================================================

s2Member has been designed to make optimum use of core WordPress
functions. It does not add its own tables to your site’s database, but
instead uses the regular WordPress tables.

This means that s2Member’s functionality can easily be extended by using
other plugins, even if they have not been designed specifically with
s2Member in mind. Below is a list of plugins that integrate particularly
well with s2Member, organized according to the function that they
provide.

Please note that this list is *not* exhaustive. It simply lists those
plugins that we have either used ourselves or that have been reported by
s2Member users as integrating well with s2Member.

Admin Bar {#admin-bar .unnumbered}
---------

[Admin Bar Disabler](https://wordpress.org/plugins/admin-bar-disabler/)

This plugin enables you to show or hide the admin bar to users with
specific user roles (including s2Member levels).

Caching {#caching .unnumbered}
-------

[WP Super Cache](https://wordpress.org/plugins/wp-super-cache/)

[W3 Total Cache](https://wordpress.org/plugins/w3-total-cache/)
(provided that object caching is not enabled)

[Zen Cache](https://wordpress.org/plugins/zencache/)

[Zen Cache Pro](https://zencache.com/) (paid plugin)

We are the developers of Zen Cache and Zen Cache Pro, so these can
always be guaranteed to work with s2Member. Zen Cache Pro offers the
significant advantage that it makes it possible to cache content for
logged-in members. It also offers the ability to compress (minify) CSS
and javascript files, which will make your site go even faster.

Capability Management {#capability-management .unnumbered}
---------------------

[Capability Manager
Enhanced](https://wordpress.org/plugins/capability-manager-enhanced/)

[Members](https://wordpress.org/plugins/members/)

Both these plugins enable you to have much finer-grained control over
which capabilities are assigned to each user role (including s2Member
levels). This enables you, for example, to allow those with s2Member
Level 1 to have access to content that would otherwise be restricted to
those at s2Member Level 4 and above.

Perhaps more importantly, these plugins also enable you to change the
default hierarchical structure of s2Member levels. You could therefore
use either of them to prevent users at s2Member Level 2 and s2Member
Level 3 from being able to access content designated for those at
s2Member Level 1.

Changing Text Created by s2Member {#changing-text-created-by-s2member .unnumbered}
---------------------------------

[Say What?](https://wordpress.org/plugins/say-what/)

s2Member and s2Member Pro provide a variety of forms and buttons for use
on your site. You might, however, prefer to use different words or
phrases (whether in English or another language) instead of the default
s2Member text. This plugin (which, when activated, will appear in your
Tools menu under Text Changes) enables you to do so easily by simply
filling in four boxes for each phrase you wish to change.

Those boxes are as follows:

1.  Original string: type in the current text

2.  Text Domain: type \`\`s2member” (without the quotes)

3.  Text Context: type \`\`s2member-front” (without the quotes)

4.  Replacement String: type in your desired text

Comment Subscriptions {#comment-subscriptions .unnumbered}
---------------------

[Comment Mail](https://wordpress.org/plugins/comment-mail/)

[Comment Mail Pro](http://comment-mail.com/) (paid plugin)

We are the developers of both these plugins. They allow commenters to
sign up for email notifications whenever they leave a comment on your
site. Or, they can also subscribe without commenting — the choice is
theirs.

This is a fantastic way to engage visitors — giving them the details
they want, when (and how) they want them!

Counting Hits on Posts and Pages {#counting-hits-on-posts-and-pages .unnumbered}
--------------------------------

[Post Views Counter](https://wordpress.org/plugins/post-views-counter/)

This plugin provides a means of displaying how many times a post or page
has been viewed. There are options for displaying in the admin pages
and/or on the front end, and it is possible to exclude visits by those
with specific roles (including s2Member roles) from being counted.

Groups Management {#groups-management .unnumbered}
-----------------

[KC Groups
Management](http://krumch.com/2013/07/09/kc-groups-management/#.Vklev3q350w)
(paid plugin)

This enables one user to purchase a bundle of s2Member memberships that
s/he can then control. This is very useful if, for example, you have a
corporate client who wishes to enable access for a number of employees.

Identifying Post and Page IDs {#identifying-post-and-page-ids .unnumbered}
-----------------------------

[Reveal IDs](https://wordpress.org/plugins/reveal-ids-for-wp-admin-25/)

[WP Show Ids](https://wordpress.org/plugins/wp-show-ids/)

Sometimes, when using s2Member, you might wish to protect a specific
post or page and need to obtain its ID. Both these plugins add the ID
number of each post and page to the lists of posts and pages in the
WordPress admin pages.

Login and Registration {#login-and-registration .unnumbered}
----------------------

[Clean Login](https://wordpress.org/plugins/clean-login/)

[Sidebar Login](https://wordpress.org/plugins/sidebar-login/)

Clean Login provides a means of creating new login, lost password, and
registration pages using regular WordPress pages. It also provides a
setting to disable the admin bar for every user except administrators.
Just make sure that the option to “Disable dashboard access for
non-admin users?” is left unchecked, so that that can be managed by
s2Member instead.

Sidebar Login, as its name suggests, provides a means of adding a login
widget to any sidebar.

Note that s2Member Pro also provides its own widget that can be placed
in any sidebar so as to enable a member to login on any post or page
where that widget appears.

MailChimp Integration {#mailchimp-integration .unnumbered}
---------------------

[KC S2M+MC](https://wordpress.org/plugins/kc-s2mmc/)

s2Member already enables basic integration capabilities with MailChimp.
This plugin takes that integration much deeper, so that users can be
added either from s2Member or from MailChimp, and they will be synced
across to the other application.

Menus {#menus .unnumbered}
-----

[Nav Menu Roles](https://wordpress.org/plugins/nav-menu-roles/)

[Privilege Menu](https://wordpress.org/plugins/privilege-menu/)

If you enable all Alternative View Protections in s2Member (or check the
Nav Menus box option) then s2Member will ensure that menu items will
reflect the user role of the current user. In other words, someone at
s2Member Level 1 will see on the menu only those items that are
accessible to someone with that user level.

These two plugins offer more fine-grained control. You might, for
example, wish someone with s2Member Level 1 access to be able to see a
menu item that is accessible only for someone at s2Member Level 2 so
that this can act as a \`\`teaser,” encouraging them to purchase an
upgrade.

PHP in Posts and Pages {#php-in-posts-and-pages .unnumbered}
----------------------

[ezPHP](https://wordpress.org/plugins/ezphp/)

There are other plugins that also offer the capability to add PHP code
to posts and pages. However, we are the developers of the ezPHP plugin,
and recommend it because, besides the regular PHP syntax, it provides an
alternative way of inserting PHP that uses shortcodes. This makes it
possible to use on the visual editor of a post or page, as well as on
the text editor.

Protected Downloads Management and Tracking {#protected-downloads-management-and-tracking .unnumbered}
-------------------------------------------

[s2Member Secure File
Browser](https://wordpress.org/plugins/s2member-secure-file-browser/)

This plugin provides fine-grained control of your protected file
downloads (including downloads served inline). It also enables you to
track how many times a file has been downloaded, and by whom.

Spam Prevention {#spam-prevention .unnumbered}
---------------

[Ban Hammer](https://wordpress.org/plugins/ban-hammer/)

[Anti-Spam by
CleanTalk](https://wordpress.org/plugins/cleantalk-spam-protect/)

[WP-SpamShield Anti-Spam](https://wordpress.org/plugins/wp-spamshield/)

So long as you are using the default WordPress registration form, Ban
Hammer provides a way of preventing registrations from users with email
domains that you can specify.

The other two plugins provide more general spam protection on login and
registration forms, including forms generated by s2Member and s2Member
Pro.

User Data: Listing, Searching, and Sorting {#user-data-listing-searching-and-sorting .unnumbered}
------------------------------------------

[AMR Users](https://wordpress.org/plugins/amr-users/)

[AMR Users Plus
s2Member](https://wpusersplugin.com/downloads/amr-users-plus-s2-member/)
(paid plugin)

s2Member Pro provides an <span>[</span>s2Member-List /<span>]</span>
shortcode that makes it possible for site owners to build a list of
their members in a variety of ways. The shortcode might be used to
present a list of your highest ranking members, or simply to provide
other members with a way to search for each other. There are a lot of
use cases for this, and the shortcode is quite flexible. More details
are
[here](https://s2member.com/kb-article/s2member-list-shortcode-documentation/).

If, however, you have some other use case that this shortcode does not
cater for, these two plugins provide other ways to build lists of your
members.

Widgets {#widgets .unnumbered}
-------

[Display Widgets](https://wordpress.org/plugins/display-widgets/)

This plugin adds a series of options to each active widget that enable
you to control not only the posts, pages, categories, etc. on which the
widget appears, but also which user roles (including s2Member user
roles) will be able to see it.

**Comment by jaswsinc** [comment]
@KTS915 Excellent! Thanks so much.
I'm adding this to my list for the weekend so we can move this to the live site.

**Comment by jaswsinc** [comment]
Referencing a [slightly modified version of this article](https://github.com/websharks/s2member-kb/issues/280) that is being prepared for our KB.

~ Closing this issue in favor of #280
