### ISSUE TITLE
Plugins that work well with s2Member

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#280]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [Plugins that work well with s2Member](http://s2member.com/kb-article/plugins-that-work-well-with-s2member/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/tutorials/2016/280-plugins-that-work-well-with-s2member.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/tutorials/2016/280-plugins-that-work-well-with-s2member.md)

---

**Comment by jaswsinc** [comment]
@raamdev Please review and publish whenever you have some time. I cleaned this up just a bit to format things for our KB. It should be fine as-is, but any additional tweaks that you'd like to add now or in the future would be awesome also.

**Comment by raamdev** [comment]
@jaswsinc I believe we discussed publishing this as a blog post on s2Member.com as opposed to a KB Article. Is that still the intention or do you feel this would be better as a KB Article?

**Comment by jaswsinc** [comment]
Either would be great with me. Actually, since this is probably going to be updated over and over again; i.e., as a list that we try to keep, maybe we could publish this as a KBA, and then blog _about_ it—providing a link which leads to the KBA.

Totally fine with me either way though.

**Comment by raamdev** [comment]
> since this is probably going to be updated over and over again; i.e., as a list that we try to keep, maybe we could publish this as a KBA, and then blog about it—providing a link which leads to the KBA.

Yep, I agree with that approach. I'll publish this as a KB Article. Thanks!

**Comment by jaswsinc** [comment]
@raamdev  Bump :-)

**Comment by jaswsinc** [comment]
Woohoo! Thanks Raam :smiley_cat:

**Comment by Peter-FB** [comment]
You could update mentions and links of "ZenCache" to "Comet Cache". :)

**Comment by raamdev** [comment]
@Peter-FB Fixed. Thanks! 😄
