### ISSUE TITLE
How to identify S2Member protected Posts in Database

### ISSUE THREAD

**Issue by KTS915** [websharks/s2member-kb#282]
A user on the wordpress.org forum raised this question, and I referred him to the relevant KB article, but it seems it might be inaccurate.

Take a look at this thread: https://wordpress.org/support/topic/how-to-identify-s2member-protected-posts?replies=5#post-7771960

**Comment by jaswsinc** [comment]
TY for the heads up. I left a reply there the other day, but forget to close this. Appreciated :-)
