### ISSUE TITLE
EOT Renewal/Reminder Emails for Next Payment Time

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#283]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [EOT Renewal/Reminder Emails for Next Payment Time](http://s2member.com/kb-article/eot-renewalreminder-emails-for-next-payment-time/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/tutorials/2015/283-eot-renewalreminder-emails-for-next-payment-time.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/tutorials/2015/283-eot-renewalreminder-emails-for-next-payment-time.md)

---

**Comment by eryno** [comment]
@jaswrks, forgive me for zombie-ing this old ticket, but the "How can we improve this?" link on https://s2member.com/kb-article/eot-renewalreminder-emails-for-next-payment-time/ sent me here.

I found this article while I was trying to figure out whether or not s2Member could send emails out to folks whose subscriptions are about to expire. We couldn't find the feature in the interface, nor in any help documentation or feature lists. This kb article is the only thing I could find on [s2member.com](https://s2member.com) that mentions it-- I can infer that it must exist (if this isn't out of date?) from the article. It seems to me that the documentation would be improved by giving the renewal email feature its own page (which the title implies this will be, but it's missing a lot of the content I'd expect.)

I know we, for one, would have already given you our $90 if we could determine conclusively and comprehensively which features are available in Pro. 

Thanks!
