### ISSUE TITLE
re: Does s2Member guard against brute-force attacks by monitoring failed login attempts?

### ISSUE THREAD

**Issue by ckalech** [websharks/s2member-kb#289]
How can the number of attempts be modified?
Can an IP Address be whitelisted?

**Comment by clavaque** [comment]
These may help you: _WP Admin -> s2Member -> Restriction Options_
![2017-03-12_132340-s2-restriction-options](https://cloud.githubusercontent.com/assets/2848808/23831707/3e5d4846-0727-11e7-9085-575b2cee9f2c.png)

**Comment by raamdev** [comment]
@ckalech s2Member supports some basic protections, yes. See:

- s2Member → Restriction Options → Bruce Force IP/Login Restrictions
- s2Member → Restriction Options → Simultaneous Login Restrictions
- s2Member → Restriction Options → Unique IP Access Restrictions

If you need to configure things further with regards to security, I recommend installing a plugin designed specifically for that purpose, such as [Wordfence](https://www.wordfence.com/) or [Jetpack](https://jetpack.com/) (which comes with several security features).
