### ISSUE TITLE
Integrating ClickBank with s2Member

### ISSUE THREAD

**Issue by kristineds** [websharks/s2member-kb#290]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [Integrating ClickBank with s2Member](http://s2member.com/kb-article/integrating-clickbank-with-s2member/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/tutorials/2016/290-integrating-clickbank-with-s2member.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/tutorials/2016/290-integrating-clickbank-with-s2member.md)

---

**Comment by jaswsinc** [comment]
Woohoo! Lookin' good :-)

**Comment by raamdev** [comment]
:+1:

**Comment by kristineds** [comment]
@jaswsinc @raamdev This is ready for review. :) Looking forward to your feedback.

**Comment by raamdev** [comment]
@kristineds Wooohooo! This looks awesome! :smile: I'd say this is 95% done. :-) Nice work.

Here's some feedback:

---

> ranked as one of the most highly-trafficked

I would say "highly-visited" not "trafficked", which has a slightly negative connotation (e.g., "human trafficking"). 

> If you are planning to use Clickbank as your preferred payment gateway

I would add "with s2Member" to the end of that ("as your preferred payment gateway with s2Member").

> use Clickbank as your preferred payment gateway

I noticed you have "Clickbank" in some places and "ClickBank" elsewhere; please standardize on "ClickBank", which is how they refer to themselves on their website.

> Enable ClickBank gateway on s2Member

Change to "Enable ClickBank Gateway Inside s2Member"

> 1) First, activate the ClickBank payment gateway

Whenever you're switching contexts, please indicate where the action should be performed, e.g., "1) First, inside s2Member activate the..."

> 2) On your ClickBank account,

"Inside your ClickBank account". Also, the screenshot in this step needs arrows pointing to the Edit buttons in the top right.

> In that area that appears, you will need to provide a description and tick all boxes to each option. Click the Save button.

"In that area that appears, fill in a description (e.g., "s2Member Integration") and tick..."

> 3) Go to Dashboard → s2Member → ClickBank Options → ClickBank Account Details, enter your ClickBank username

Switching contexts again here, so I would start this with "Inside s2Member, go to Dashboard..."

> To configure this, you would need to set up two things:

"you will need to" not 'would'.

> 1) Create a secret key on your ClickBank account

"inside your ClickBank account" not 'on'

> 2) You will then need to go back to Advanced Tools section again and click Edit once more. Copy the IPN URL found on the ClickBank IPN v2.1 or v6 Integration section and enter it on the Instant Notification URL field found on your ClickBank account (Settings → My Site → Advanced Tools → Edit). Click on the Save Changes button.

This is confusing. More context-switching here that isn't clear. Where is "Advanced Tools section"? Where is "ClickBank IPN v2.1 or v6 Integration"?

**Comment by raamdev** [comment]
@kristineds One thing that would nicely wrap up this article is a section at the bottom titled "Using s2Member-generated ClickBank Buttons" that includes a screenshot of the s2Member ClickBank Buttons section and explains that with ClickBank integration complete, those buttons can now be generated to provide paid access to the site.

**Comment by kristineds** [comment]
@raamdev Thanks for the thorough feedback! I have updated the article and added the section for the ClickBank buttons. This is ready for review. :smile:

**Comment by kristineds** [comment]
@raamdev Any updates on this? :smiley:

**Comment by raamdev** [comment]
@kristineds Woohoo! Very nice. This is 99% done. :-) Here's the last bit of feedback: 

---

> Enable ClickBank gateway Inside s2Member

- [ ] 'gateway' should be 'Gateway'. 

- [ ] Also, right under this title I suggest adding a note: "_**Note:** ClickBank integration is only available with s2Member Pro._"

> In that area that appears

- [ ] Should be, "In the area that appears"

> You can choose to either use IPN v2.1 URL or IPN v6 URL.

How do I know which one to use? I don't see anything about this inside s2Member and none of your ClickBank screenshots seem to mention it--that seems like an obvious question someone would ask when setting this up...

- [ ]  Oh, I see later on in the Step 4 screenshot that the version is selected when you configure the URL inside ClickBank. We should mention this... "You can choose to either use IPN v2.1 URL or IPN v6 URL (you'll choose the version when you configure the URL inside your ClickBank account; we recommend using v6 unless ClickBank says to use v2.1)."

> How Do I Integrate ClickBank with s2Member?

- [ ] I suggest changing the title to "Integrating ClickBank with s2Member" and then changing the category to `tutorials`; this seems more like a full tutorial than a question.

**Comment by kristineds** [comment]
@raamdev I have updated the article per your feedback. Thank you. :)

**Comment by raamdev** [comment]
@kristineds **Approved as of 2016-03-18**. :-) Nice work!

**Comment by kristineds** [comment]
:smile:

**Comment by kakarr0t** [comment]
There's just one problem I see.  Under Clickbank Buttons, I don't see any instructions on where to paste the code generated from creating the Clickbank Button.

"Very simple. All you do is customize the form fields provided, for each Membership Level that you plan to offer. Then press (Generate Button Code). These special ClickBank Buttons are customized to work with s2Member seamlessly."

The Instructions explain how to create the button, and to some degree the usefulness of the button, however, it never explains where/on what form/in what menu/etc to paste this code.

**Comment by kakarr0t** [comment]
It would also be helpful to explain how to utilize the Clickbank Thank-You Page under the Clickbank Options within s2member.

**Comment by raamdev** [comment]
@kakarr0t Thank you for the feedback. The button shortcodes can be placed on any WordPress Post/Page, the same as with any other WordPress shortcodes. The s2Member Getting Started guide suggests that you insert them "into your Membership Options Page", but really they can go anywhere you like.

**Comment by renzms** [comment]
Hi @raamdev , for this Clickbank tutorial article - https://s2member.com/kb-article/integrating-clickbank-with-s2member/

The link where it says
>1) Sign up for a ClickBank Merchant Account here: https://accounts.clickbank.com/public/#/signup/form/key/ (if you don't have an existing account yet)

redirects to an error page `So sorry`

![sorry](https://user-images.githubusercontent.com/13220018/29021389-f6290c00-7b97-11e7-93f9-80c6c51c02ff.png)


Would be nice if it could be updated to: https://accounts.clickbank.com/signup/

**Comment by raamdev** [comment]
Fixed. Thanks @renzms!
