### ISSUE TITLE
s2member registration form

### ISSUE THREAD

**Issue by lp901** [websharks/s2member-kb#291]
I have the s2member plugin. The registration form is defined under s2member - general options - registration/profile fields & options. I have some fields defined as required and they appear with a * next to them. The problem is that when the form appears under "my account", those fields are in fact required. However if the member has not registered yet, the form appears on the login page, and those fields do NOT require the user to fill them in, even though they still appear with an *. I have tested the form by making some changes to titles to confirm it is in fact the SAME form appearing in both places. Can you help me with why this might be happening and how do I make those required fields be required on the login page? Thank You.

**Comment by jaswsinc** [comment]
We reserve GitHub for discussions regarding the s2Member source code, detailed bug reports, and feature requests. Customer service and technical support for s2Member are handled by our support team. Please open a trouble ticket here. We'll be happy to assist you there :-) Please visit: http://wsharks.com/1pYbliq
