### ISSUE TITLE
re: Can I offer promotional discounts or coupon codes using s2Member Pro?

### ISSUE THREAD

**Issue by Lifeischoice** [websharks/s2member-kb#298]
Can I offer promotional discounts or coupon codes using s2Member Pro?
https://s2member.com/kb-article/can-i-offer-promotional-discounts-or-coupon-codes-using-s2member-pro/

---

**Comment by Lifeischoice** [comment]
How can I test if a user has used a coupon so that if yes, I can display a pro form, otherwise the proform is hidden.

**Comment by Lifeischoice** [comment]
How can I test if a user has used a coupon on a page so that if yes, I can display a pro form, otherwise the pro form is hidden.

**Comment by jaswsinc** [comment]
We reserve GitHub for discussions regarding the s2Member source code, detailed bug reports, and feature requests. Customer service and technical support for s2Member are handled by our support team. Please open a trouble ticket here. We'll be happy to assist you there :-) Please visit: http://wsharks.com/1pYbliq
