### ISSUE TITLE
How can I allow Signups without a Username?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#3]
If a site owner does not want to require usernames during the signup process but rather only collect the email address, first name, and last name, this can be done by hiding the username field on the Pro-Form using CSS and then auto-generating a username in the background.

Referencing: http://www.primothemes.com/forums/viewtopic.php?f=4&t=15672&p=49082#p49082

**Comment by raamdev** [comment]
Moved here: https://github.com/websharks/s2member-kb/issues/10

**Comment by milehigh420** [comment]
I'm a little confused. Can anyone help explain this to me?

I want the username to be email. But I don't want to ask someone twice for email and username if they're going to be the same. But I don't even know where to add this CSS?

I built my form in the free registration part of s2 design section. It links to mailchimp and I have krumch's plugin to synch everything and it's working good. I use a direct link on my site for people to register and login. So I don't even know where (a php file?) to add CSS to make this change. Is javascript needed too?

I also thought that wordpress didn't allow emails as usernames? Has this been changed?

But I also plan on having another free registration page linked to another list in MC. I now realize that I cannot create two of these within S2. Correct me if I'm wrong. So I'll have to design it in MC and then have it synced to s2 with the krumch plugin. Right? But bc of this workflow, how would I synch MC's email to a username? Is this even possible? Or is there another way to create multiple free registration forms linked to MC in S2 with custom MC merge fields?

Thanks for any insight you can provide.

**Comment by raamdev** [comment]
@milehigh420 This issue has been moved here: [Using the Email Address as the Username](https://github.com/websharks/s2member-kb/issues/10). There are instructions over there explaining how to do this and how it works.
