### ISSUE TITLE
Installing s2Member

### ISSUE THREAD

**Issue by patdumond** [websharks/s2member-kb#300]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue draft and either questions or tutorials
- [x] Add required YAML configuration
- [x] Add Tags for this KB Article to the YAML config (see YAML Keys (Explained))
- [ ] Edit and finalize draft for publishing (remove draft label, add draft-finalized label)
- [ ] Create Markdown file for this Article (remove draft-finalized label, add pending label)
- [ ] Publish KB Article (remove pending label, add published label; leave this step for the Project Lead)

```yaml
title: Installing s2Member
categories: tutorials
tags: s2member-users-guide, s2member
author: patdumond
github-issue: https://github.com/websharks/s2member-kb/issues/300
```
This Knowledge Base Article covers installing both the free *s2Member Framework* and the *s2Member Pro Add-on*. The *s2Member Framework* is the free plugin available from the [WordPress.org Plugin Repository](https://wordpress.org/plugins/s2member/). *s2Member Pro* is an add-on to the *s2Member Framework* which adds features to the base plugin. You must have the *s2Member Framework* installed to use *s2Member Pro*.   

*This article is part of the [s2Member User's Guide](http://s2member.com/kb/kb-tag/s2member-users-guide/), a series of articles that cover the fundamentals of using s2Member.*

## Installing the s2Member Framework

The *s2Member Framework* can be installed straight from *WordPress.org*. From **WordPress Dashboard → Plugins → Add New**, type <kbd>s2Member</kbd> into the **Search box** and press <kbd>Enter</kbd>. The *s2Member Framework* should be the first plugin displayed in the grid. Click **Install Now**.

![add-plugins-rsz](https://cloud.githubusercontent.com/assets/9320495/14572810/042bcdb2-031f-11e6-826d-d84cbf2460d6.jpg)

The plugin will install. Once you see *Successfully installed the plugin s2Member Framework...*, click **Activate Plugin**. That's usually all there is to installing the *s2Member Framework*. 

If you have any problems installing the *Framework* through the *WordPress* plugin directory, you can install the *Framework* using FTP instead.

### Alternative Installation Method: Using FTP

- Download the *s2Member Framework* zip file from your account at *s2member.com*. 
- Extract the files from the zip file. Inside the top-level folder you've extracted, you'll find the `s2member` folder.
- Log in to your web server using FTP.
- Navigate to the plugins folder for your installation of *WordPress*. This is `/wp-content/plugins/` by default.
- Upload the `s2member` folder to your plugins folder.
- After the files have uploaded you should see the following new folders in your plugins folder:
    - `s2member`
    - `s2member-files`
    - `s2member-logs`

Go into your WordPress Dashboard: **WordPress Dashboard → Plugins**. You should see *s2Member Framework* listed as an inactive plugin. Click **Activate**.

![activate-s2member-rsz](https://cloud.githubusercontent.com/assets/9320495/14572826/111a5458-031f-11e6-96c2-802706379d20.jpg)

## Installing the s2Member Pro Add-on

If you've already configured the *s2Member Framework*, you might be concerned about losing your settings when you install the *s2Member Pro Add-on*. There's no reason to be concerned, but *s2Member* features a setting to prevent losing your configuration when deactivating the plugin. 

Go to **WordPress Dashboard → s2Member → General Options → Plugin Deletion Safeguards**. Make sure this is set to the default of **Yes(safeguard all data/options)**. Then click the **Save All Changes** button at the bottom of the page. 

**Tip**: *It is a good idea to always leave this set to* **Yes** *unless you are absolutely sure you will no longer be using s2Member on a website.*

**Note**: *You must install the s2Member Framework before installing the s2Member Pro Add-on.*

- Download the *s2Member Pro Add-on* zip file from your account at *s2member.com*. 
- Extract the files from the zip file. Inside the top-level folder you've extracted, you'll find the `s2member-pro` folder.
- Log in to your web server using FTP.
- Navigate to the plugins folder for your installation of *WordPress*. This is `/wp-content/plugins/` by default.
- Upload the `s2member-pro` folder to your plugins folder.
- After the files have uploaded you should see the following new folders in your plugins folder:
    - `s2member`
    - `s2member-files`
    - `s2member-logs`
    - `s2member-pro`

To verify that you completed this step properly, please make sure that you have the following file path:

`/wp-content/plugins/s2member-pro/pro-module.php`

If instead, you have double `/s2member-pro/s2member-pro/` directories nested inside each other, please correct this before you continue. **In other words, if you unzipped the folder inside itself, this will cause problems.** You should have: `/wp-content/plugins/s2member-pro/pro-module.php`, along with several other files and subdirectories.

![plugins-folder-contents-rsz](https://cloud.githubusercontent.com/assets/9320495/14572829/1df3ffbc-031f-11e6-8d84-e2d8f8192bab.jpg)

Go into your WordPress Dashboard, **WordPress Dashboard → Plugins**. You should see something like **s2Member Pro 160303** listed next to the version number in the plugin listing for the *s2Member Framework*. 

![dashboard-plugins-pro-activated-rsz](https://cloud.githubusercontent.com/assets/9320495/14572836/26e03faa-031f-11e6-970e-c201c6e8f20b.jpg)

**Comment by patdumond** [comment]
@jaswsinc & @raamdev: Next installment in the *s2Member User's Guide* -- *Installing s2Member* first draft submitted for review.

Thanks in advance.

**Comment by jaswsinc** [comment]
Thanks Pat! :-) Glad to see these still coming in. Awesome 🎉 

## Quick Review

> into the Search box and press [[Enter]]

**Tip:** You can use the `<kbd>` tag for this; i.e., _into the Search box and press <kbd>Enter</kbd>_

```
into the Search box and press <kbd>Enter</kbd>
```

_That gave me a good reason to add a note about `<kbd>` in [this wiki article](https://github.com/websharks/team/wiki/KB-Articles-::-Formatting-Rules---Special-Cases#keyboard-keys)._

---

> This is \wp-content\plugins\ by default.

I suggest using `/` instead of `\` as a standard for file system paths. That way we can reserve `\` for Windows-specific documentation and/or PHP namespace references that actually do use `\` instead.

---

> Installing the s2Member Framework Using FTP

In this section I think you accidentally used `s2member-pro` instead of just `s2member`.

> Note: You must install the s2Member Framework before installing the s2Member Pro Add-on.
> Deactivate the s2Member Framework before installing the s2Member Pro Add-on.

In the pro installation instructions, I would try to clarify the first two steps just a bit. It states that I need to have the Framework installed first, but then it says that I need to deactivate the Framework before I begin. That seems slightly confusing to me. I think what you're trying to do there is give them a path to easily identifying the s2Member Pro Add-On being listed beside the Framework once it is uploaded; e.g., reactivating the Framework and seeing s2Member Pro mentioned there. Having the Framework disabled (while not necessary), does seem like a more logical path to discovery of the Pro Add-On, but as it stands now I think it might confuse some people when they read the first two steps.

**Comment by patdumond** [comment]
@jaswsinc: Thanks for the tip about `<kbd></kbd>`! I modified the section on installing *s2Member Pro* to remove references to deactivating and then activating the *s2Member Framework*.

@raamdev: This article is ready for your review.

**Comment by raamdev** [comment]
@patdumond Looks great! Here's some feedback:

---

> This Knowledge Base Article covers installing both the free s2Member Framework and the s2Member Pro Add-on.

I suggest adding a few more sentences to the introduction that explains the difference between the Framework and the Pro Add-On, i.e., that the Framework is the base plugin and the Pro Add-On is just that: an add-on to the Framework that adds additional functionality. I'd also mention here that the Framework is required to use the Pro Add-On (I know it's mentioned in the _Installing the s2Member Pro Add-on_ section, but it's good to reiterate this point).

> That's all there is to installing the s2Member Framework. If you have any problems or if you are going to install the s2Member Pro Add-on immediately, you can also install the Framework using FTP.

The first sentence here makes it sound like you're done talking about _s2Member Framework_, so I'm caught off guard when you say "you can also install the Framework using FTP." 

I suggest moving that first sentence to the end of the previous paragraph, and then changing the second sentence to "If you have any problems installing the Framework through the WordPress plugin directory, you can alternatively install the Framework using FTP."

> Installing the s2Member Framework Using FTP

I suggest renaming this to "Alternate Method: Installing via FTP". As it is now, when I skim the article it seems like I have to install the Framework via the Plugin Directory _and_ do something with FTP. 

> - Upload the `s2member-pro` folder to your plugins folder.

This doesn't seem to belong in the "Installing the s2Member Framework Using FTP" section.

> Installing the s2Member Pro Add-on

I suggest adding a sentence at the start of this section addressing the scenario where someone has already been using the s2Member Framework and has already configured it. In that scenario, a very common question is "will I lose my s2Member Framework configuration?" 

It would be good to add a sentence or two that explains how the Plugin Deletion Safeguards (when enabled) will prevent the loss of any existing configuration and that installing the s2Member Pro Add-On will simply activate additional features in the Framework—no existing configuration will be lost and all Framework functionality will remain accessible.

> Deactivate the s2Member Framework before installing the s2Member Pro Add-on.

I suggest adding a note here explaining that no existing configuration will be lost if Plugin Deletion Safeguards are enabled.

> After the files have uploaded you should see the following new folders in your plugins folder:

Each of the plugin folder names in the list that follows this sentence should be in code style. (This applies to both sections where you list the folders.)

> This is `\wp-content\plugins\` by default.

I suggest changing those to forward-slashes (`/`). I realize that backslashes are used on Windows systems, but the rest of the paths in this article are using forward-slashes, so it should be kept consistent.

> You will see **s2Member Pro vxxxxxx** listed next to

I suggest saying, "You will see something like **s2Member Pro v160303** listed next to". Readers can infer from the format what is intended, even if the version number doesn't match what they have.

**Comment by patdumond** [comment]
@raamdev, @jaswsinc: All requested revisions made. Ready for final review.

**Comment by jaswsinc** [comment]
Looks fantastic Pat! Thanks so much :-) I love the screenshots.

I only noticed one minor issue. This sentence has some unparsed asterisks.

> Tip: It is a good idea to always leave this set to *Yes** unless you are absolutely sure you will no longer be using s2Member on a website.*

**Comment by patdumond** [comment]
@jaswsinc wrote:
> only noticed one minor issue. This sentence has some unparsed asterisks.

I caught that before I saw your response. :)

**Comment by raamdev** [comment]
Marking this as **approved as of 2016-05-05**.
