### ISSUE TITLE
re: Does s2Member offer me any sort of badge or security certificate that I can display?

### ISSUE THREAD

**Issue by RandyKing** [websharks/s2member-kb#308]
Does s2Member offer me any sort of badge or security certificate that I can display?
http://s2member.com/kb-article/does-s2member-offer-me-any-sort-of-badge-or-security-certificate/

---
Haven't found it yet, but would like to know what PHP code is generated to display the Security Badge.  I have a custom theme implementation with a child theme and the automatic footer insertion does not appear to be working.  Would do it manually if I can find the PHP for it.

**Comment by jaswsinc** [comment]
We reserve GitHub for discussions regarding the s2Member source code, detailed bug reports, and feature requests. Customer service and technical support for s2Member are handled by our support team. Please open a trouble ticket here. We'll be happy to assist you there :-) Please visit: http://wsharks.com/1pYbliq
