### ISSUE TITLE
Configuring s2Member Support for Stripe

### ISSUE THREAD

**Issue by patdumond** [websharks/s2member-kb#312]
##### KB Article Creation Checklist
- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [Configuring s2Member Support for Stripe](http://s2member.com/kb-article/configuring-s2member-support-for-stripe/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/tutorials/2016/312-configuring-s2member-support-for-stripe.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/tutorials/2016/312-configuring-s2member-support-for-stripe.md)

---

**Comment by patdumond** [comment]
@jaswsinc, @raamdev: Broken out of *Configuring Payment Gateways* (https://github.com/websharks/s2member-kb/issues/306). Ready for review. (Should be easier since each article is now much shorter.

**Comment by jaswsinc** [comment]
@patdumond Looks fantastic.

@raamdev Looks good-to-go. The only thing I noticed is that the `help section` link should be a redirection instead; e.g., `s2member.com/r/...`.

@patdumond If you're able to find a redirection link in the Dashboard you can update the article above. Otherwise, I think Raam might be willing to update this as a part of the final publication.

**Comment by patdumond** [comment]
@raamdev: I updated the link @jaswsinc mentioned. Ready for your review.

**Comment by CKMacLeod** [comment]
Might be nice to have guidance for which event types to include. 

Also the page at S2Member (like a lot of them) is full of broken images for me.
