### ISSUE TITLE
Configuring s2Member Support for Authorize.net

### ISSUE THREAD

**Issue by patdumond** [websharks/s2member-kb#313]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [Configuring s2Member Support for Authorize.net](http://s2member.com/kb-article/configuring-s2member-support-for-authorize-net/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/tutorials/2016/313-configuring-s2member-support-for-authorize-net.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/tutorials/2016/313-configuring-s2member-support-for-authorize-net.md)

---

**Comment by patdumond** [comment]
@jaswsinc, @raamdev: Broken out of *Configuring Payment Gateways* (https://github.com/websharks/s2member-kb/issues/306). Ready for review. (Should be easier since each article is now much shorter.

**Comment by jaswsinc** [comment]
@patdumond Another fantastic article. Thanks for breaking these apart.

@raamdev Looks good-to-go as far as I'm concerned. The only thing I see is there are two links that should probably be associated with redirections instead; e.g., `s2member.com/r/...`.

@patdumond If you've able to find those redirects in the Dashboard panel you can update them in the article above. Otherwise I think Raam might be willing to do that as a part of the final publication.

**Comment by patdumond** [comment]
@raamdev: I updated the links @jaswsinc requested I change. Ready for your review.
