### ISSUE TITLE
Forms for Free Registration and Level Access

### ISSUE THREAD

**Issue by patdumond** [websharks/s2member-kb#316]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue draft and either questions or tutorials
- [x] Add required YAML configuration
- [x] Add Tags for this KB Article to the YAML config (see YAML Keys (Explained))
- [x] Edit and finalize draft for publishing (remove draft label, add draft-finalized label)
- [x] Create Markdown file for this Article (remove draft-finalized label, add pending label)
- [x] Publish KB Article (remove pending label, add published label; leave this step for the Project Lead)

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [Forms for Level 0 (Free Registration) to Level x Access](http://s2member.com/kb-article/forms-for-level-0-free-registration-to-level-x-access/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/tutorials/2016/316-forms-for-level-0-free-registration-to-level-x-access.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/tutorials/2016/316-forms-for-level-0-free-registration-to-level-x-access.md)

---

**Comment by jaswsinc** [comment]
> In this article, we will show you how to generate Pro-Forms for membership-level access

Suggest title caps for 'Membership-Level Access'

---

This screenshot seems to have the paragraphs in the body selected maybe. If possible, I'd like to see a version of this screenshot without the text selected.

![](https://cloud.githubusercontent.com/assets/9320495/17379329/e50e9bea-598f-11e6-96b4-d96ca5e28fdc.jpg)

---

> See Generating Membership Forms with s2Member Pro-Forms and Buttons (Overview) (https://github.com/websharks/s2member-kb/issues/315) for a description of the form fields used in these Pro-Forms.

Suggest making clickable text out of the link in this paragraph; i.e., instead of the URL itself, use the link to make some of the text clickable.

---

Everything else looks great to me. cc @raamdev for final review & publication.

**Comment by raamdev** [comment]
In addition to Jason's notes, here are a few more:

----

> Addon

Should be "add-on".

> Use of a Free Registration Form will override your Open Registration configuration.

I suggest specifying the path to the "Open Registration" setting.

> S2Member Shortcode Attributes Explained

Should be "s2Member"

> Forms for s2 Member Level 1-4 Access

Should be "s2Member"

**Comment by raamdev** [comment]
I also suggest changing the title of this article from "Forms for Level 0 (Free Registration) to Level x Access" to "Forms for Free Registration and Level Access".

**Comment by patdumond** [comment]
@jaswsinc, @raamdev: Made requested revisions to this KBA.
