### ISSUE TITLE
Generating Member Registration Access Links

### ISSUE THREAD

**Issue by patdumond** [websharks/s2member-kb#320]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue draft and either questions or tutorials
- [x] Add required YAML configuration
- [x] Add Tags for this KB Article to the YAML config (see YAML Keys (Explained))
- [x] Edit and finalize draft for publishing (remove draft label, add draft-finalized label)
- [x] Create Markdown file for this Article (remove draft-finalized label, add pending label)
- [x] Publish KB Article (remove pending label, add published label; leave this step for the Project Lead)

---

### KB Article Published @ s2member.com<br />:page_with_curl: See: [Generating Member Registration Access Links](http://s2member.com/kb-article/generating-member-registration-access-links/)
[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/tutorials/2016/320-generating-member-registration-access-links.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/tutorials/2016/320-generating-member-registration-access-links.md)

---

**Comment by patdumond** [comment]
@jaswsinc, @raamdev: Next article in the s2Member User's Guide series for your review.

**Comment by jaswsinc** [comment]
@patdumond Nice!

> You can then use the CCAP code to set appropriate content restrictions for your website.

Suggest changing this to:

You can [use CCAPs](http://s2member.com/kb-article/video-custom-capabilities-for-wordpress/) to set custom content restrictions for your website.

---

> This data is numeric value followed by a space and then a single letter representing the period. D – Day | W – Week | M – Month | Y – Year | L - Lifetime

I suggest making this clearer if you can. Maybe use list items to show the list of terms, and then provide examples for this field in backticks to help a user understand what should be entered here.

**Comment by jaswsinc** [comment]
> Custom Capabilities (CCAP)

CCAP should be 'CCAPs' (plural) in this context.

**Comment by jaswsinc** [comment]
> use the CCAP code

Avoid using 'CCAP code' and instead just say 'CCAP' or 'CCAPs'. The word 'code' can be somewhat misleading because 'code' is vague and we don't use it in other places within the documentation.

**Comment by patdumond** [comment]
@jaswsinc: Made your requested revisions. Great suggestions, by the way.

**Comment by avawendt** [comment]
The new link generated also says it is expired.  I even added the filter  the "link expired error" KB article gave: 's2-hacks.php'
Almost two years later and it is still a problem?
My non-profit client cannot afford PayPal Pro, so we are using only Buy it Now single vs. recurring subscriptions.
