### ISSUE TITLE
re: Can I customize emails that s2Member sends?

### ISSUE THREAD

**Issue by smallcircles** [websharks/s2member-kb#322]
It would be "amazing" if that article would actually tell you WHERE you can customize such emails, and other notifications for that matter....

Can I customize emails that s2Member sends?
https://s2member.com/kb-article/can-i-customize-emails-that-s2member-sends/

---

**Comment by raamdev** [comment]
@smallcircles Thank you for the suggestion! I have updated that article to include notes about where the templates can be found: https://s2member.com/kb-article/can-i-customize-emails-that-s2member-sends/
