### ISSUE TITLE
re: Can I display a member directory?

### ISSUE THREAD

**Issue by 5-high** [websharks/s2member-kb#324]
Can I display a member directory?
https://s2member.com/kb-article/can-i-display-a-member-directory/

---
This is a really useful article but it doesn't explain how to link each member's name to their personal profile.
And without this a members' list is useless.
I have been trying to do this unsuccessfully for a while now (using the pro version without buddypress), and despite other forum members trying to help I can't get the shortcodes to work. Please see my topic in the forum for details: https://forums.wpsharks.com/t/add-link-to-profile-from-display-name-in-members-list/1635
I think it would be a really useful tutorial/article to add to your knowledge base. Thanks.

**Comment by raamdev** [comment]
@5-high I clarified things a bit in my response here: https://forums.wpsharks.com/t/add-link-to-profile-from-display-name-in-members-list/1635/12?u=raamdev

**Comment by 5-high** [comment]
Thanks - i have a better understanding of it now. Much appreciated.
