### ISSUE TITLE
Authorize.NET Disabling TLS

### ISSUE THREAD

**Issue by bcolflesh** [websharks/s2member-kb#327]
Anything in s2Member that needs updated for this?
-----------------

As you may be aware, new PCI DSS requirements state that all payment systems must disable early TLS by June 30, 2018.

In preparation for this requirement, Authorize.Net plans to disable TLS 1.0 and TLS 1.1 on the following dates:

Production: February 28, 2018 

We have disabled the sandbox in advance of production to allow you and your developer time to test your website or payment solution and ensure you are no longer using TLS 1.0 or 1.1 prior to February 28th.

**Comment by jaswrks** [comment]
@bcolflesh s2Member, in its current state, is ready for this change. However, I suggest sending an email to your web host or reviewing their blog for updates about TLSv1.2. Ask your host to confirm that your server is running a modern version of the cURL library that's used by WordPress/s2Member, preferably cURL v7.34 or higher. Also ask them to confirm that cURL is using OpenSSL v1.0.1c or higher.
