### ISSUE TITLE
re: Is the free version of s2Member still being actively developed and maintained?

### ISSUE THREAD

**Issue by ghost** [websharks/s2member-kb#331]
Is the free version of s2Member still being actively developed and maintained?
https://s2member.com/kb-article/is-the-free-version-of-s2member-still-supported/

---

**Comment by ghost** [comment]
3 years old date on this- is it still being developed?

**Comment by clavaque** [comment]
Thanks for mentioning this! Yes, seeing a very old date could make one wonder. I changed the date to a slightly closer one.

And yes, it is still being developed, please see my announcement here: https://forums.wpsharks.com/t/happy-new-year-big-announcement/5443/30
