### ISSUE TITLE
Can we set recurring payment for 0 level using stripe payment ?

### ISSUE THREAD

**Issue by imranpatel4444** [websharks/s2member-kb#332]
Hello All,

I want to setup 3 level membership.

Level 0 for $0.5 for 7 days after than using recurring payment it will be auto upgrade to level 1 and auto pay $10 for level 1 membership for 1 month.

Is this possible ?

Can we set recurring payment for 0 level using stripe payment ?

Waiting for you replay

Thank you

**Comment by clavaque** [comment]
Hi Imran,

This repo is to track our knowledge base ideas and articles. https://s2member.com/kb/

The support forum can be found here: http://forums.wpsharks.com

Answering your question quick, though:

you can't sell level 0, that's always for free signups, or demotions from higher levels. You can sell Level 1 or higher, though. You could give give an initial term of 7 days for 50 cents, and a recurring monthly term at $10.

User level doesn't change automatically, except for EOT demotions to Level 0, not for higher levels. You could use some PHP to change his level, though. https://s2member.com/kb-article/rolescapabilities-via-php/

For it to happen after 7 days, see: _WP Admin > s2Member >  API / Scripting > Content Dripping_  

If you need anything else, see you over at the forums. :)

I hope that helps!
