### ISSUE TITLE
What emails does s2Member allow me to customize?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#40]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Create Markdown file for this Article (remove `draft-finalized` label, add `pending` label)
- [x] Publish KB Article (remove `pending` label, add `published` label; leave this step for the Project Lead)

---

**Markdown File:** http://wsharks.com/1Eq9pEF
**Published KB Article:** http://s2member.com/kb-article/what-emails-does-s2member-allow-me-to-customize/

---

**Comment by raamdev** [comment]
This article should also mention the **Registration Access Link** email that s2Member sends out when using Buttons. @jaswsinc is there even a way to customize that email?

**Comment by jaswsinc** [comment]
> @jaswsinc is there even a way to customize that email?

That would be the Signup Confirmation Email (Standard); under the PayPal Options, for instance.

**Comment by raamdev** [comment]
> That would be the Signup Confirmation Email (Standard);

Oh! Right. For some reason I was thinking that was a different email. Thanks for clarifying! :)
