### ISSUE TITLE
How can I hide specific fields on the [s2Member-Profile /] form?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#46]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

**Markdown File:** http://wsharks.com/1D9RHaG
**Published KB Article:** http://s2member.com/kb-article/how-can-i-hide-specific-fields-on-the-s2member-profile-form/

---

**Comment by jaswsinc** [comment]
Great. Nice article!

**Comment by jaswsinc** [comment]
Adding tag `mu-plugins-hacks`.

**Comment by raamdev** [comment]
@jaswsinc I'd like to update this article to include an example of how you can hide a specific Custom Field. Right now it only shows how you can hide all Custom Fields via `ws_plugin__s2member_during_profile_during_fields_display_custom_fields`.

I tested this and it seems to do the job, hiding a custom field with an ID of `country_code`. Any feedback?

```php
add_filter('ws_plugin__s2member_during_profile_during_fields_during_custom_fields_display', '__hide_custom_field_country_code', 10, 2);

function __hide_custom_field_country_code($boolean, $vars) {
    if($vars['field_var'] == 'country_code')
        return FALSE;
	else
		return TRUE;
}
```

**Comment by jaswsinc** [comment]
Looks great to me.

**Comment by raamdev** [comment]
@jaswsinc Cool, thanks! :)

**Comment by jaswsinc** [comment]
Regarding the latest addition...

I suggest adding an opening `<?php` tag to the code sample, and a line above the code sample that shows where to save this code; i.e., please create: `/wp-content/mu-plugin/this-code.php`

---

> inside an Must-Use Plugin

Should be: `a Must-Use Plugin` right?

**Comment by raamdev** [comment]
> and a line above the code sample that shows where to save this code; i.e., please create:

lmao... how did I miss that? Fixed. 

> Should be: a Must-Use Plugin right?

Ha, yes, correct. Fixed. Thanks!

**Comment by hausmanconsulting** [comment]
I'm trying to update a site from an old version of WP and I'm getting this error when using this method:

PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function s2member_hide_certain_fields(), 1 passed in /home/xyz/wp-includes/class-wp-hook.php on line 287 and exactly 2 expected in /home/xyz/wp-content/themes/mytheme-child/functions.php:429

That line 429 is:
`function s2member_hide_certain_fields($boolean, $vars) {`

Changing the line to:

`function s2member_hide_certain_fields($vars) {`

seems to work, but I worry I'm breaking something without checking to see if anyone else has any additional info. I'm not using $boolean or $vars in the function, but I don't know if those values are needed later in the code.

ETA: here's the add_filter line, which is a little different than the example given:

`add_filter('ws_plugin__s2member_during_profile_before_fields', 's2member_hide_certain_fields', 10, 2);`
