### ISSUE TITLE
Why are my Custom Registration Fields not appearing on the Pro-Form?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#48]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

**Markdown File:** http://wsharks.com/1AoQSDM
**Published KB Article:** http://s2member.com/kb-article/why-are-my-custom-registration-fields-not-appearing-pro-form/

---

**Comment by raamdev** [comment]
@jaswsinc I seem to recall there being another scenario where Custom Registration Fields don't show up... was it on Upgrade Pro-Forms for users who are already logged in?

**Comment by jaswsinc** [comment]
> was it on Upgrade Pro-Forms for users who are already logged in?

Yes. Existing users are not asked for those details again. Instead, the `[s2Member-Profile /]` is used for existing members, where you can ask them to update their Profile with that form.

**Comment by raamdev** [comment]
@jaswsinc Thank you! Article updated. :)

**Comment by jaswsinc** [comment]
- Converting Dashboard paths to bold text instead of backticks.
- Adding tags `login-registration, registration-profile-fields, pro-forms, troubleshooting`.
- A few wording changes and general cleanup.
