### ISSUE TITLE
My Pro Form looks nothing like examples I've seen, why?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#50]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

**Markdown File:** http://wsharks.com/1GIh8B9
**Published KB Article:** http://s2member.com/kb-article/my-pro-form-i/

---

**Comment by jaswsinc** [comment]
Adding the following list item...

- Test your Pro Forms in a default WordPress installation (e.g. a default theme such as Twenty Fiftteen, Twenty Fourteen, and with only the s2Member plugin active). This will rule out a possible conflict with other plugins or a custom theme's CSS file. If you find that s2Member's default structural styles (i.e. the CSS that it comes with by default) is not enough to override styles presented by your theme, or it conflicts with your theme; then you may need to seek assistance from a developer to help resolve these conflicts by introducing additional CSS in your theme's `style.css` file.

**Comment by raamdev** [comment]
I've seen this question more than once! Will definitely be referencing this KB Article in the future.

Also, I added the missing `questions` label.
