### ISSUE TITLE
Setting up Two Membership Types (Professional / Student) with Two Sub-Types (Gold / Bronze) and a 3-Day Free Trial

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#51]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

**Markdown File:** http://wsharks.com/1Eq41RN
**Published KB Article:** http://s2member.com/kb-article/setting-up-two-membership-types-professional-student-with-two-sub-types-gold-bronze-and-a-3-day-free-trial/

---

**Comment by raamdev** [comment]
#### What if we want to only show an upgrade form that matches the type of account they originally had?

_I didn't include this in the tutorial mostly because it would've added to the complexity of the tutorial. However, this is almost certainly going to be a follow-up question to anyone who follows this tutorial in the real world. I'm including notes here on how this tutorial could be extended, or even better, made into a second tutorial._

We could change the default EOT Behavior to leave the Custom Capabilities alone when downgrading the account, then just make sure all content is restricted to Level 1 + CCAPs. On the Login Welcome Page, we could check if Level == 0 and if so, check Custom Capabilities associated with that account (which would tell us what account type they originally registered for) and then show the appropriate upgrade form for that specific type of account.

**Comment by jaswsinc** [comment]
Great article! One of the best articles I've seen for s2Member. Nice :-)



> We could change the default EOT Behavior to leave the Custom Capabilities alone when downgrading the account, then just make sure all content is restricted to Level 1 + CCAPs. On the Login Welcome Page, we could check if Level == 0 and if so, check Custom Capabilities associated with that account (which would tell us what account type they originally registered for) and then show the appropriate upgrade form for that specific type of account.

That's a good reason for s2Member not to delete the `custom` value whenever it does an EOT. I'll try to update the software before the next release so that is not the case. If the `custom` value was not deleted, it too could be used to track different types of accounts.

```
custom="example.com|type-a"
```

```php
<?php if(strpos(get_user_field('s2member_custom'), '|type-a') !== FALSE): ?>
   A type-a account.
<?php endif; ?>
```

**Comment by raamdev** [comment]
> If the `custom` value was not deleted, it too could be used to track different types of accounts.

Ah, great idea!

**Comment by WAPFLondon** [comment]
Hi. I have a similar problem. I need two membership types. We have videos for sale from two countries, each with its own membership fee. So I need people to be able to be Country A, Country B or Country A & B. Is this possible please?
