### ISSUE TITLE
How do I force a specific EOT with the Advanced Import/Export Tools?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#52]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

- [x] Screenshots and links to [existing KB article on s2member.com (old site)](http://www.s2member.com/kb/advanced-import-tools/) need to be updated once that KB article has been moved over to the new site.

---

**Markdown File:** http://wsharks.com/1MOcimu
**Published KB Article:** http://s2member.com/kb-article/how-do-i-force-a-specific-eot-with-the-advanced-importexport-tools/

---

**Comment by jaswsinc** [comment]
@raamdev I got the article(s) you were waiting for on the new site.
http://s2member.com/kb/kb-q/importing/

**Comment by raamdev** [comment]
@jaswsinc This looks ready to me now.

**Comment by jaswsinc** [comment]
Cool, thanks!

**Comment by jaswsinc** [comment]
Published this article: http://s2member.com/kb-article/how-do-i-force-a-specific-eot-with-the-advanced-importexport-tools/
