### ISSUE TITLE
Why am I getting "Input Error: K: Format Of Site Key Was Invalid"?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#56]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

- [x] ~~Update KB Article link for "Configuring CAPTCHA Anti-Spam Security with Your Own reCAPTCHA Keys" with the correct link to the Live Article~~ No longer necessary after latest WPKBA updates.

---

**Markdown File:** http://wsharks.com/1Eq7vny
**Published KB Article:** http://s2member.com/kb-article/why-am-i-getting-input-error-k-format-of-site-key-was-invalid/

---

**Comment by jaswsinc** [comment]
Great article! 

I changed, "message that say "Input Error: K" 
to, "message that says "Input Error: K"
