### ISSUE TITLE
Video Tutorial: Wrapping Multiple Pro-Form Shortcodes as Checkout Options

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#57]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

**Markdown File:** http://wsharks.com/1EUU0Pm
**Published KB Article:** http://s2member.com/kb-article/wrapping-multiple-pro-form-shortcodes-as-checkout-options/

---

**Comment by jaswsinc** [comment]
Agree. That would be really helpful. Are you planning to do the video or you would like a volunteer?

**Comment by raamdev** [comment]
> Are you planning to do the video or you would like a volunteer?

It's up for grabs. I created this GitHub Issue because it came to mind while I was replying to a ticket where the KB Article I wrote earlier wasn't enough to explain things. I realized a video would've helped make everything crystal clear. :)

**Comment by jaswsinc** [comment]
Copy that. I'll take the video then.

**Comment by jaswsinc** [comment]
The video will be live here momentarily: http://youtu.be/WWn3jWQpMSg

**Comment by raamdev** [comment]
> The video will be live here momentarily: http://youtu.be/WWn3jWQpMSg

Awesome. Thank you! I've updated the KB GitHub Issue checklist and YAML config.
