### ISSUE TITLE
When is an EOT Time set for each user?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#58]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

- [x] Try to make this article a little bit clearer even.

---

**Markdown File:** http://wsharks.com/1wZwaQb
**Published KB Article:** http://s2member.com/kb-article/when-is-an-eot-time-set-for-each-user/

---

**Comment by jaswsinc** [comment]
Adding a TODO item above...
> Try to make this article a little bit clearer even.

**Comment by raamdev** [comment]
Updated the checklist to separate out the additional TODO with `##### Additional TODOs`; this helps make it obvious that the new checklist item is not part of the default checklist (i.e., it stands out better as "something additional that needs to get done before this can be published").

**Comment by jaswsinc** [comment]
> separate out the additional TODO with ##### Additional TODOs

Ah, good idea. Thanks!

**Comment by jaswsinc** [comment]
Spiffed this article up a bit. Making it a little clearer.

**Comment by raamdev** [comment]
Updated the article with a new section: **What happens if an EOT was already set and the user "renews"?*

**Comment by jaswsinc** [comment]
There is a reference to ZenCache.com in the last section of this article that seems out of context to me.

**Comment by raamdev** [comment]
> There is a reference to ZenCache.com in the last section of this article that seems out of context to me.

Good catch. Fixed.
