### ISSUE TITLE
How can I change how much Users are paying for access?

### ISSUE THREAD

**Issue by brucewsinc** [websharks/s2member-kb#59]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Create Markdown file for this Article (remove `draft-finalized` label, add `pending` label)
- [x] Publish KB Article (remove `pending` label, add `published` label; leave this step for the Project Lead)

---

**Markdown File:** http://wsharks.com/1FIlXsE
**Published KB Article:** http://s2member.com/kb-article/how-can-i-change-how-much-my-paypal-customers-are-paying-for-access/

---

**Comment by raamdev** [comment]
@brucewsinc Woohoo! So good to see your first KB article here. :)

---

Some feedback / thoughts after reading this draft: If the site owner wanted to provide a way of allowing their existing subscribers to change their current subscription, couldn't the site owner use a Billing Modification Form? 

![2015-01-22_20-52-23](https://cloud.githubusercontent.com/assets/53005/5868508/98a8c58e-a278-11e4-96fb-cd8ebfe87870.png)

**Comment by brucewsinc** [comment]
> couldn't the site owner use a Billing Modification Form?
Good point, and thanks for the screenshot.

**Comment by brucewsinc** [comment]
I updated this article to include information Billing Modification Forms.

**Comment by raamdev** [comment]
> It's noteworthy to add that these forms don't actually update the User's current subscription, but cancels their Subscription, and creates a new one. Thereby requiring that the User check out again (i.e. re-enter their payment information).

Right. That's an important thing to point out.

> I updated this article to include information Billing Modification Forms.

Awesome. Thanks!

---

One more suggestion and then I promise to go away. :) Whenever you're mentioning various sections of the plugin, please try to make complete references to the areas, e.g., **Dashboard → s2Member (Pro) → PayPal Pro-Forms → PayPal Pro Billing Modification Forms**. This will _really_ help readers of the article, as there's a good chance they're not as familiar with the plugin as us and screenshots often don't show how to get to the area shown in the screenshot.

If you use Typinator or some other macro-like program, I recommend creating shortcuts to common sections so you're not retyping these every time you need to mention them. :)

**Comment by brucewsinc** [comment]
> e.g., Dashboard → s2Member (Pro) → PayPal Pro-Forms → PayPal Pro Billing Modification Forms

The reason I didn't do that here is because this varies depending on the Payment gateway, but it could be added as an example. Let me see if I can squeeze it in.

**Comment by raamdev** [comment]
> because this varies depending on the Payment gateway

Right, but if you're showing screenshots that are gateway-specific anyway, you may as well show pointers for navigating to the areas in the screenshots. You can then just mention something like "If you're not using PayPal as your payment gateway, you'll want to navigate to the applicable section."
