### ISSUE TITLE
How can I style Pro Forms w/ custom CSS?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#6]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

**Markdown File:** http://wsharks.com/1CzD00O
**Published KB Article:** http://s2member.com/kb-article/how-can-i-style-pro-forms-w-custom-css/

---

**Comment by Jamman** [comment]
CSS styling for the return from PayPal page (mydomain.com/?s2member_paypal_return=1) does not seem to load theme css - not sure why this would be outside it...?

Might be good to include instructions on how to change css for this too.

**Comment by jaswsinc** [comment]
@Jamman Thanks for the feedback on this.

We we generally suggest instead of customizing that page, is to use a different page entirely; i.e., one that _is_ a part of your own theme. This can be accomplished with the `success=""` shortcode attribute in your button and/or Pro-Form—assuming you are using s2Member Pro.

See: **Dashboard → s2Member → PayPal Pro-Forms → Custom Return URLs Upon Success**
