### ISSUE TITLE
How can I change the order of the Pro-Form fields?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#61]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

- [x] Add that this could be possible with s2Member's custom pro-form templates (and link to a tutorial for setting those up!)

---

**Markdown File:** http://wsharks.com/1914hva
**Published KB Article:** http://s2member.com/kb-article/how-can-i-change-the-order-of-the-pro-form-fields/

---

**Comment by brucewsinc** [comment]
@raamdev It may be useful to add that this could be possible with s2Member's custom pro-form templates (or maybe that would be a topic for another KB article).

**Comment by raamdev** [comment]
> It may be useful to add that this could be possible with s2Member's custom pro-form templates (or maybe that would be a topic for another KB article).

Ah, great suggestion! Thank you! Adding a todo to this draft's checklist.

**Comment by brucewsinc** [comment]
If you look for `%%custom_fields%%` in any of the Pro-Form templates that support them, you can move the fields that way, following the instructions here:

http://www.s2member.com/kb/pro-forms/#customizing-pro-forms

**Comment by brucewsinc** [comment]
> Adding a todo to this draft's checklist.
Cool!
