### ISSUE TITLE
Why are my shortcodes showing up as plain text?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#63]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

**Markdown File:** http://wsharks.com/1Eq01kf
**Published KB Article:** http://s2member.com/kb-article/why-are-my-shortcodes-showing-up-as-plain-text/

---

**Comment by jaswsinc** [comment]
**Another reason this can occur...**

Did you receive a notice in your Dashboard about there being an update available for s2Member? If you complete an update of the s2Member Framework, and then somehow miss the second notice that pops up after this, which explains that s2Member Pro needs to be updated also; you will end up with an outdated copy of s2Member Pro.

So what's happening is that you have a newer version of the Framework, with an outdated version of the Pro add-on. The Pro add-on is designed NOT to load unless both versions match up. Until you complete the second portion of the update, all pro functionality (e.g. pro shortcodes) will be unavailable.

Solution: update your copy of the s2Member Pro add-on.

**Comment by raamdev** [comment]
> Another reason this can occur...

Ah, thanks for adding this!
