### ISSUE TITLE
Why are users who login via the Pro Login Widget denied access to the Login Welcome Page?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#64]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

- [x] Add link to www vs non-www and/or SSL vs non-SSL KB article.

---

**Markdown File:** http://wsharks.com/1EpZtuT
**Published KB Article:** http://s2member.com/kb-article/why-are-users-who-login-via-the-pro-login-widget-denied-access-to-the-login-welcome-page/

---

**Comment by raamdev** [comment]
Hmm, further testing indicates this KB article is likely invalid. Users with the "Subscriber" role have no problem accessing the Login Welcome page.

**Comment by jaswsinc** [comment]
That's correct. Anyone who can log in and has the `read` capability in WordPress, can access the LWP. Every user in WordPress can access the core built-in `read` capability.

**Comment by raamdev** [comment]
@jaswsinc Thank you. I've updated the KB article and left it as an unfinished draft until we have a www vs non-www and/or SSL vs non-SSL KB article that we can link to.
