### ISSUE TITLE
How do I get rid of the "Create Profile" section on my Pro Form?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#65]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

**Markdown File:** http://wsharks.com/1EpYTNF
**Published KB Article:** http://s2member.com/kb-article/how-do-i-get-rid-of-the-create-profile-section-on-my-pro-form/

---

**Comment by jaswsinc** [comment]
You can also choose not to ask the user to become a member. For instance, if you use s2Member's Specific Post/Page functionality, those forms only ask for the name/email; i.e. it's a quick purchase that does not require an account to be registered.

**Comment by raamdev** [comment]
> use s2Member's Specific Post/Page functionality, those forms only ask for the name/email

Great point! Thanks. I've updated the KB Article.
