### ISSUE TITLE
Can I customize the IP Restrictions template file?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#66]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

#### Additional TODO Items

- [x] Update the link which leads to the "Hacking s2Member" page once the KB is moved over.

---

---

**Markdown File:** http://wsharks.com/1EpYxqr
**Published KB Article:** http://s2member.com/kb-article/can-i-customize-the-ip-restrictions-template-file/

---

**Comment by ethanpil** [comment]
I was able to get this working for me in s2-hacks.php:

````
//Redirect IP Restriction to pretty page
add_action('ws_plugin__s2member_during_ip_restrictions_ok_no', 's2hack_exit_503_func');
function s2hack_exit_503_func($vars)
{
	unset($__refs, $__v); # s2Member does this within /includes/classes/ip-restrictions.inc.php above it's exit(), so you should too.
	header("Location: http://url.com/access-restriction/");
}
````
