### ISSUE TITLE
Automatically Redirecting to a Protected Page after Login

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#7]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

- [x] Figure if a note about s2Member's own redirection functionality needs to be added to this KB article (see [comment](https://github.com/websharks/s2member-kb/issues/7#issuecomment-72379495))

---

**Markdown File:** http://wsharks.com/1CzAIid
**Published KB Article:** http://s2member.com/kb-article/automatically-redirecting-to-a-protected-page-after-login/

---

**Comment by KTS915** [comment]
@raamdev,

This is extremely helpful. In fact, this whole series of KB articles is very helpful. Thanks for putting them together!

I do have a question about this one. 

I use wp_redirect(home_url()); so that it is possible to login only from the site's home page. Unfortunately, this seems to cause the wp_login_url( esc_url($URI) ) in the code above to have no effect. Presumably, the URI attributes do not get passed on by the redirect.

Is there a way to modify the code so that it will work even with logins from the home page?

**Comment by raamdev** [comment]
> This is extremely helpful. In fact, this whole series of KB articles is very helpful. Thanks for putting them together!

@KTS915 Thank you! We're going to be using these KB Article drafts here on GitHub to power a new knowledge base on a redesigned s2Member website, so what you're seeing here are just our drafts. We're using GitHub to draft KB articles specifically so that we can receive feedback like you're providing here! :)

> I use wp_redirect(home_url());

Can you explain how and where you're using `wp_redirect(home_url());`?

**Comment by KTS915** [comment]
@raamdev Well, I have been reading and learning a lot!

Thanks for responding! I am using this code in my functions.php file to force all logins through my home page:

function possibly_redirect(){
  global $pagenow;
  if ( 'wp-login.php' == $pagenow ) {
    if ( isset( $_POST['wp-submit'] ) ||   // in case of LOGIN
      ( isset($_GET['action']) && $_GET['action']=='logout') ||   // in case of LOGOUT
      ( isset($_GET['checkemail']) && $_GET['checkemail']=='confirm') ||   // in case of LOST PASSWORD
      ( isset($_GET['checkemail']) && $_GET['checkemail']=='registered') ) return;    // in case of REGISTER
    else wp_redirect(home_url());
    exit();
  }
}
add_action('init','possibly_redirect');

In case it matters, I use the Clean Login plugin to provide the login form (via a shortcode) for that page. It respects the s2Member Welcome page redirection, so I don't think it's causing any issue in addition to the redirect, but I'm not a developer so I can't be 100% sure.

**Comment by raamdev** [comment]
> I am using this code in my functions.php

Ah, I see what you're doing. Well, yes, in that case the `wp_login_url( esc_url($URI) )` won't have the expected effect because after `wp_login_url( esc_url($URI) )` redirects to the login page _with_ the proper post-login redirection URL (i.e., the URL to be redirected to after login), your code ignores that extra information (the `$URI`) and redirects to `home_url()`.

In your situation, you'd need to update the example I provided in the KB article so that it redirects to the Home Page instead of redirecting to `wp_login_url()`. You'd also need to pass the `$URI` to the Home Page as a query string and then read that query string on the Home Page login form so that when someones uses the login form on the home page it redirects to `$URI` after logging in.

You'd do something like `wp_redirect(home_url('?login_redirect_uri='.esc_url($URI)))`. You would then need to check `$_REQUEST['login_redirect_uri']` to see if it is set, and if it is set, then configure your login form to redirect to that page after login (how you configure it will depend on whatever plugin you're using or whatever custom code you have for the login form).

See the [`home_url()` Codex Documentation](http://codex.wordpress.org/Function_Reference/home_url) for more details.

**Comment by KTS915** [comment]
Thank you very much, Raam!

I have put that in my MOP and it is now automatically redirecting to the home page with the URI. Very nice!

Now to work out how to utilize that information ...

Thanks again!

**Comment by KTS915** [comment]
Raam,

On the basis of the code modification you provided, my developer has got the redirection working perfectly for regular WordPress roles. Thank you!

Unfortunately, though, it's not working for s2member roles, which are still being directed to the regular Welcome page. Is there some specific code he needs to use to override the regular s2Member redirect on login?

**Comment by jaswsinc** [comment]
@KTS915 Reviewing this file and the way s2Member handles redirections could help.
https://github.com/websharks/s2member/blob/000000-dev/s2member/includes/classes/login-redirects.inc.php#L43

**Comment by KTS915** [comment]
Thanks, @jaswsinc -- that was fast!!

I have passed this information on to my developer.

**Comment by KTS915** [comment]
@raamdev and @jaswsinc,

The code Jason pointed me to reminded me of some code I had seen before, though I can't now either remember or locate the source. But putting it into my functions.php file seems to have done the trick. (I suppose I could now move it to my s2hacks.php file in mu-plugins). 

In case it's useful to anyone else, here it is:

function s2_redirect($redirect, $vars = array()) {
	if ( (isset($_GET['action']) && $_GET['action'] != 'logout') || (isset($_POST['login_location']) && !empty($_POST['login_location'])) ) {
		$redirect = $_SERVER['HTTP_REFERER'];
		return $redirect;
	}
}
add_filter("ws_plugin__s2member_login_redirect", "s2_redirect", 10, 2);

Thanks very much!!

**Comment by aliyevanv** [comment]
Hi, I tried using the code, but it doesn't seem to work.  What I'm trying to achieve is for my users to be taken to whatever page they were on before logging in, bypassing the login welcome page.  I inserted this code into funcs.inc.php  Was that a wrong place for it?  Sorry, I'm not a developer, so "for dummies" answer would be really helpful.  Thanks in advance!

**Comment by aliyevanv** [comment]
I also tried inserting the code into login-redirects.inc.php and login-redirects-r.inc.php but it didn't work either.

**Comment by raamdev** [comment]
> I tried using the code, but it doesn't seem to work.

What code did you try using? Can you copy/paste it here for me?

**Comment by aliyevanv** [comment]
Hi!  I just copy-pasted the entire code you provided on the top of this page.  I pasted it at the end of funcs.inc.php file

// Filter wp_nav_menu() to add a login/logout link to the nav menu
add_filter( 'wp_nav_menu_items', 'my_nav_menu_login_link', 10, 2 );
function my_nav_menu_login_link($menu, $args) {

    if( $args->theme_location == 'primary' ) { // The name of your nav menu location, see http://codex.wordpress.org/Navigation_Menus#Display_Menus_on_Theme

        // If the user is logged in, show logout link, otherwise show login link
        if (is_user_logged_in())
        {
            $logout_link = '<li><a href="' . wp_logout_url() .'" title="Logout">Logout</a></li>';
            $menu        = $menu.$logout_link;
            return $menu;
        }
        else
        {
            // If a the visitor was attempting to access a protected page, extract the URI
            if(!empty($_REQUEST["_s2member_vars"]))
                @list($restriction_type, $requirement_type, $requirement_type_value, $seeking_type, $seeking_type_value, $seeking_uri)
                    = explode("..", stripslashes((string)$_REQUEST["_s2member_vars"]));

            if (!empty($seeking_uri)) {
                $URI = base64_decode($seeking_uri);
            }

            // If we have a link to redirect to after login, use it, otherwise use the default login URL
            if(!empty($URI)) {
                $login_link = '<li><a href="' . wp_login_url( esc_url($URI) ) .'" title="Login">Login</a></li>';
                $menu        = $menu.$login_link;
            }
            else {
                $login_link = '<li><a href="' . wp_login_url() .'" title="Login">Login</a></li>';
                $menu        = $menu.$login_link;
            }
        }
    }

    return $menu;
}

**Comment by raamdev** [comment]
@aliyevanv Please see [the full KB Article](https://github.com/websharks/s2member-kb/blob/master/tutorials/2015/7-automatically-redirecting-to-a-protected-page-after-login.md).

**Note: That the code only works from the Membership Options Page.** It will only redirect a user who clicks a login link _from the Membership Options Page_, after they have been redirected to the Membership Options Page because they tried to access some protected content. This code _does not_ simply redirect a visitor to any previous page they were on.

Also, the exact code to use will depend on your WordPress theme. If you're not familiar with WordPress theme development and/or PHP, please consult with your theme developer to find out exactly how the following code should be implemented.

**Comment by aliyevanv** [comment]
@raamdev Thanks for the explanation!  I don't have a theme developer, I use a free theme that I tweaked myself.  I'll try to make it work using your suggestions.  Thank you!

**Comment by oyegigi** [comment]
@raamdev  Is there any way to implement this using the [s2Member-Login /] shortcode to display the login form directly on the membership options page rather than forcing them to click a link, then log in?

**Comment by philipt18** [comment]
I was wondering if this article could be updated to reflect the fact the ezPHP is no longer available, and any other updates that may be needed for PHP 7, Gutenberg, etc. @clavaque
