### ISSUE TITLE
Manually Deactivating s2Member

### ISSUE THREAD

**Issue by brucewsinc** [websharks/s2member-kb#71]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Create Markdown file for this Article (remove `draft-finalized` label, add `pending` label)
- [x] Publish KB Article (remove `pending` label, add `published` label; leave this step for the Project Lead)

---

**Markdown File:** http://wsharks.com/1GIvmlz
**Published KB Article:** http://s2member.com/kb-article/manually-deactivating-s2member/

---

**Comment by raamdev** [comment]
Related to #70.

**Comment by jaswsinc** [comment]
- Adding the `troubleshooting` tag.
- A few changes in wording.

**Comment by raamdev** [comment]
This article should mention that you need to rename the `s2member` directory back to `s2member` before reactivating the plugin, otherwise reactivation fails.

**Comment by raamdev** [comment]
Also, if you do try to activate s2Member after the `s2member` directory has been renamed (as the KB Article currently instructs you to do), s2Member throws some errors and fails to activate and a bunch of extra s2Member directories are created with the renamed version of the folder, which will add to even more confusion:

![2015-05-12_19-30-02](https://cloud.githubusercontent.com/assets/53005/7600826/6e73d842-f8dd-11e4-9aca-f94e78391034.png)

**Comment by jaswsinc** [comment]
> This article should mention that you need to rename the s2member directory back to s2member before reactivating the plugin, otherwise reactivation fails.

Done. Thanks!
