### ISSUE TITLE
How Do Members Cancel Their Membership?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#75]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

**Markdown File:** http://wsharks.com/1EB6FUZ
**Published KB Article:** http://s2member.com/kb-article/how-do-members-cancel-their-membership/

---

**Comment by jaswsinc** [comment]
Moving this to the Soft Launch Milestone because it seems like an important topic to cover in the KB.

**Comment by jaswsinc** [comment]
@raamdev Free memberships can be cancelled (so-to-speak), by setting an EOT Time on the account just like any other. That's assuming that a free user is actually being allowed to access Membership Level 1 (or higher). That's possible through the use of a Free Registration Pro-Form.

In short, Level 0 is as low as you can go. If you want to "cancel" free users, content should be protected at Level 1 or higher, so that demoting a free user back to Level 0 will effectively "cancel" their access.

Thus, cancelling a free user involves demoting the user to Level 0; i.e., changing their Role using the WordPress Dashboard.

**Comment by raamdev** [comment]
@jaswsinc I see the Billing Modification Forms only allow downgrading to Level 1--i.e., there's no option to downgrade to Level 0. Is downgrading to Level 0 possible by changing `level="0"`, or no?

I'm wondering if there's some way to allow members in a free membership-type system to "cancel" (i.e., downgrade) their account on their own.

**Comment by jaswsinc** [comment]
@raamdev writes...
> I'm wondering if there's some way to allow members in a free membership-type system to "cancel" (i.e., downgrade) their account on their own.

Unfortunately, no. When this has come up in the past one of my suggestions has been to create a button on your own to accomplish this, and I have pointed others to this article: http://s2member.com/kb-article/rolescapabilities-via-php/ about how to downgrade or upgrade users via PHP.

**Comment by jaswsinc** [comment]
Great article! http://s2member.com/kb-article/how-do-members-cancel-their-membership/

**Comment by drrule** [comment]
I am missing one simple step here,.  How do I add the short code to "my account" page?  All that is currently is the shortcake for the membership, is there a way to add that to the tab somehow?  Sorry for the newbie question, but I could use a bit more direction.

You can then link to the "Cancel Membership" page from their "My Account" page (i.e., the Login Welcome Page). When a member cancels their membership using the form, their recurring subscription will be canceled on the payment gateway and their account will be downgraded as per your Automatic EOT Behavior settings (WordPress Dashboard → s2Member → Stripe Options → Automatic EOT Behavior).

**Comment by raamdev** [comment]
@drrule You can put the shortcode (that you generate in **s2Member → [Payment Gateway] Pro-Forms → [Payment Gateway] Billing Cancellation Forms**) anywhere you like. We generally recommend creating a separate Page called "Cancel Membership" and then place the shortcode on that page. Then on your "My Account" page, you simply have a link that says, "If you want to cancel your membership, click here.", and the 'here' would be a link to the "Cancel Membership" page.

**Comment by clairemount** [comment]
So I have a question once someone cancels and they are downgraded to Level 0 are they then subscribed to the autoresponder list assigned to Level 0?

**Comment by jaswsinc** [comment]
Yes, that is correct. However, you'll need to enable that functionality.
See: Dashboard → s2Member → API / List Servers → **Automate Un-Subscribe/Opt-Outs?**
