### ISSUE TITLE
Are Basic Download Restrictions required?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#77]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

**Markdown File:** http://wsharks.com/1GIthpG
**Published KB Article:** http://s2member.com/kb-article/are-basic-download-restrictions-required/

---

**Comment by raamdev** [comment]
Added a paragraph to the end of this draft to help clarify what's happening.

**Comment by jaswsinc** [comment]
Thanks!

Updating
> s2Member Level's

to
> s2Member Levels

**Comment by raamdev** [comment]
> Level's

Ha! Thanks. :)

**Comment by jaswsinc** [comment]
Changing tags to: `download-options, basic-download-restrictions`.
