### ISSUE TITLE
Can I mass-update EOT Times?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#78]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

- [x] Revise the draft to clearly offer solutions for two separate scenarios: Mass-update and set to the same EOT Time (using Import/Export) and mass-extend existing EOT Times by a specific amount (i.e., using their existing EOT Time as the starting point, whatever that may be).
- [x] Update the link that references s2Member Advanced Import/Export functionality.

---

**Markdown File:** http://wsharks.com/1DCcSSS
**Published KB Article:** http://s2member.com/kb-article/can-i-mass-update-eot-times/

---

**Comment by raamdev** [comment]
Updated title use use grammatically-correct "mass-update" instead of "mass update" (_it's a mass-update, not an update about the mass_).

@jaswsinc Based on the title, I think this KB Article should also mention that if you just want to change everybody's EOT time to the same thing, you can use the Import/Export to achieve that; agreed?

**Comment by jaswsinc** [comment]
Agreed :-)

**Comment by raamdev** [comment]
I was going to tweak this draft, but then I realized the entire draft really needs to be reorganized the clearly present these two scenarios and their solutions (i.e., with headers, etc.). Added a TODO list item for this.

**Comment by jaswsinc** [comment]
> use grammatically-correct "mass-update" instead of "mass update"

Do you have a reference for this by chance? I was looking to find some clarity on this, but I find most online references are using "mass update" as two words. I was unable to find anyone else using "mass-update", and I also could not find any discussion about this particular use case.

**Comment by raamdev** [comment]
See [How to Use a Hypen](http://www.quickanddirtytips.com/education/grammar/how-to-use-a-hyphen?page=all).

As an example (these should make sense after reading the above article), here are two variations of the title where "mass update" could be written with or without the hyphen:

**Without Hyphen:** "Can I modify EOT Times with a mass update?"
**With Hyphen:** "Can I mass-update EOT Times?"

**Comment by jaswsinc** [comment]
Thanks! I see clearly that a hyphen will avoid confusion here.

Still, I find it odd that so many large companies have used "mass update" as two words.
Example: http://bit.ly/1EFU19z

I had a hard time finding any documentation on the web that uses "mass-update" in hyphenated form. I suppose, in a technical, data-oriented context, "mass update" does not require a hyphen in most cases, because the context in which it is written helps to clarify the meaning; i.e., most articles that use the phrase, "mass update" are talking about data.

I agree with you though. If it avoids confusion, it's a good thing. I don't see anything wrong with "mass-update". Using the hyphen avoids ambiguity in the same way that mass-produce or mass-market avoids ambiguity. It's just not as common.

Maybe the reason we don't see mass-update being used much, is that it doesn't match-up with the way it would be spoken. When I say, "mass-produce", I say it just like that! However, when I say, "mass-update", I say that as two words. So while I agree that writing "mass-update" avoids ambiguity, I think there is a tendency to write this as "mass update", because we don't usually say, "mass-update". We say, "mass update".

---

From this article: http://www.quickanddirtytips.com/education/grammar/how-to-use-a-hyphen?page=all

> Suspended Hyphens
> ... So if you were suspending hyphens when listing what type of vest Santa was planning on buying, you’d write that he purchased "the fire-, dog-, and soot-proof vest online."

That was new to me. I did not realize this was grammatically correct.

**Comment by raamdev** [comment]
> Maybe the reason we don't see mass-update being used much, is that it doesn't match-up with the way it would be spoken. When I say, "mass-produce", I say it just like that! However, when I say, "mass-update", I say that as two words. So while I agree that writing "mass-update" avoids ambiguity, I think there is a tendency to write this as "mass update", because we don't usually say, "mass-update". We say, "mass update".

Interesting. I'd be interested in hearing an audio recording of you pronouncing the difference between "mass-update" and "mass update". The only difference I "hear" is in my head, i.e., it _feels_ like the two words are more connected when they contain a hyphen--my brain feels like it's treating them as a single unit versus separate units. 

But as far as pronunciation, the only difference I hear when I verbally say the two words is an exaggerated difference, i.e., I need to _force_ a difference in the two. Barring the obvious differences in the words, I don't pronounce "mass update" any differently than I would pronounce "mass market" (without the hyphen).

> I suppose, in a technical, data-oriented context, "mass update" does not require a hyphen in most cases, because the context in which it is written helps to clarify the meaning

Right. That was my conclusion as well after spending about 40 minutes doing research last night. The two words are only ever used in a specific context, so people leave out the hyphen because it generally isn't necessary. However, I still feel that practice has a negative effect on non-native English speakers, and, as I love to avoid ambiguity whenever possible, I try to always use a hyphen when it will clarify the intended meaning. :-)

**Comment by jaswsinc** [comment]
> s well after spending about 40 minutes doing research last night

haha! Yep. Sorry, I spent time on it as well. One of those things I just couldn't resist.

Pronunciation: http://youtu.be/aRIPD3-uPS8

**Comment by raamdev** [comment]
> Pronunciation: http://youtu.be/aRIPD3-uPS8

Thanks!

The main reason I see the need for a hyphen is in how the two words are being used. Saying, "Can I update the EOT Times with a mass update?" sounds and looks perfectly correct to me. However, saying "Can I mass update EOT Times?" where we're using "mass update" as an action on "EOT Times" (sorry, I don't know all the technical grammar terms to describe this) seems to call for a hyphen to clarify that "mass update" is a unit, a _single action_ affecting "EOT Times". _Can I mass-update EOT Times?_

Ha, anyway, I think we've both beat this one to a pulp. Thanks for exploring the differences with me! I learned a few things. :-)

**Comment by jaswsinc** [comment]
> However, saying "Can I mass update EOT Times?" where we're using "mass update"

Thanks :-) Yep, the more I look at it now, the more it looks wrong to me also.

**Comment by jaswsinc** [comment]
I broke this down into two different solutions. 1. Import/Export 2. MU Plugin/Script

**Comment by raamdev** [comment]
> I broke this down into two different solutions. 1. Import/Export 2. MU Plugin/Script

Awesome. Looks great now!
