### ISSUE TITLE
Using a Custom Template for [s2Member-List /]

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#80]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

---

**Markdown File:** http://wsharks.com/1GIsGEx
**Published KB Article:** http://s2member.com/kb-article/using-custom-template-s2member-list/

---

**Comment by jaswsinc** [comment]
Adding `shortcodes` tag.

**Comment by Beee4life** [comment]
Update the location of where the file should be placed.

Instead of /wp-content/member-list.php it needs to be /wp-content/themes/active-theme-directory/member-list.php

**Comment by trader4300** [comment]
Instead of telling users to simply create another template file for custom member lists, actually SHOW users how this might be done with an example and a link to where they can find more information about how to do this.

**Comment by Beee4life** [comment]
If you would read the link posted above, you would find the info and how to do it... why mention something which is written down... development is not a lazy man's game... it is described, read it, do the work, don't expect others to do it for you.

**Comment by trader4300** [comment]
I thought for a long time how to respond to your immature response. The link you mention simply states to create your own template and replace the standard one. I am suggesting, to make this post more informative, to actually SHOW us how to create a template that displays all the fields we have in our members list. That would help us newbies a lot.

**Comment by Beee4life** [comment]
You have thought for long ? Dude, get a effin life.... if you would have bothered to open your eyes and read properly you would have understood the OP is a Websharks crew member, not a random user with an issue.

I was mentioning something which is incorrect... because the documentation provided display the wrong info, so others can be helped with it.

This is not a support topic or so... So please read properly before you make any dumbass comments... And I'm unsubscribing from this topic now, so making a smart ass comment will go on deaf ears... bye bye
