### ISSUE TITLE
Testing in a Clean WordPress Installation

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#81]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

**Markdown File:** http://wsharks.com/1GIsuFh
**Published KB Article:** http://s2member.com/kb-article/testing-clean-wordpress-installation/

---

**Comment by raamdev** [comment]
I was just reviewing this draft (nice!) and thought I'd suggest a few header changes to make the whole thing more _attractive_:

`Unexplained Bugs` → `Is it really a bug?`
`A Clean WordPress Test` → `Reproduce the problem in a clean WordPress environment`
`Getting Help with Conflicts?` → `How do I get help with plugin/theme conflicts?`
`Support Policy Excerpt...` → `Our Support Policy`
`Reporting Plugin Conflicts` → `How to report plugin/theme conflicts`

**Comment by jaswsinc** [comment]
Updated. Thanks!

**Comment by RealDavidoff** [comment]
How to Report Plugin/Theme Conflicts
If you identify a conflict between s2Member and another plugin, we would love to hear about this! While we cannot offer support for other 3rd-party themes/plugins, we do accept feedback. Theme/plugin conflicts are reviewed by our developers on a regular basis, and efforts to enhance compatibility are always underway. Thanks in advance for your patience!

How can we improve this article? 

>> How to Report Plugin/Theme Conflicts
>> we would love to hear about this! 
Nothing above says "HOW"??

So I can only go back to the "ticket" that linked to that page, and reply inside that "ticket".

**Comment by raamdev** [comment]
@RealDavidoff Thank you. I've added a link to the relevant area.
