### ISSUE TITLE
Which log files should I delete?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#82]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

**Markdown File:** http://wsharks.com/1GIsl4O
**Published KB Article:** http://s2member.com/kb-article/which-log-files-should-i-delete/

---

**Comment by raamdev** [comment]
Improved screenshot:

![2015-02-05_14-36-25](https://cloud.githubusercontent.com/assets/53005/6067733/a2095cf2-ad44-11e4-8d76-55d3b213a7f2.png)

**Comment by jaswsinc** [comment]
Nice!

**Comment by jaswsinc** [comment]
- Adding `troubleshooting` tag.
- Updating to improved screenshot.
- Changing backticks around Dashboard path to bold text instead.
