### ISSUE TITLE
Can a Free Subscriber register more than once?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#87]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

- [x] Also answer, "how do I prevent people from creating multiple accounts with different email addresses?".

---

**Markdown File:** http://wsharks.com/1EpXbMf
**Published KB Article:** http://s2member.com/kb-article/can-a-free-subscriber-register-more-than-once/

---

**Comment by raamdev** [comment]
This KB Article should also answer, "how do I prevent people from creating multiple accounts with different email addresses?".

**Comment by jaswsinc** [comment]
> how do I prevent people from creating multiple accounts with different email addresses?

One way would be to leave the default option here, where it requires that the end-user receive an email before they actually get their password. Of course, it's still possible to use `me+this@` or another real email address variation, but it's a deterrent at least. I think that's really all you can do.

![2015-02-05_12-34-42](https://cloud.githubusercontent.com/assets/1563559/6069753/7d359802-ad33-11e4-8258-a6acdb72b3ac.png)
