### ISSUE TITLE
If I configure fallback options with JW Player, won't that defeat the purpose of using RTMP streaming to prevent downloads?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#88]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

- [x] Update link to JW Player w/ s2Stream Shortcodes link after that tutorial has been migrated to new website.

---

**Markdown File:** http://wsharks.com/1DCcDaD
**Published KB Article:** http://s2member.com/kb-article/if-i-configure-fallback-options-with-jw-player-wont-that-defeat-the-purpose-of-using-rtmp-streaming-to-prevent-downloads/

---

**Comment by jaswsinc** [comment]
Adding the `download-options` tag.
