### ISSUE TITLE
Can iPads or iPhones play RTMP streams?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#89]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

- [x] I believe JW Player also supports HTML5 playback, which _is_ supported on iOS, so this article should be updated to include some information on that.

---

**Markdown File:** http://wsharks.com/1EpWRgx
**Published KB Article:** http://s2member.com/kb-article/can-ipads-or-iphones-play-rtmp-streams/

---

**Comment by raamdev** [comment]
I believe JW Player also supports HTML5 playback, which _is_ supported on iOS, so this article should be updated to include some information on that.

**Comment by jaswsinc** [comment]
> I believe JW Player also supports HTML5 playback, which is supported on iOS, so this article should be updated to include some information on that.

Android does also. The problem is that HTML5 video tags do not support RTMP. Therefore, Flash is required for RTMP playback through JW Player, and most mobile devices do not support Flash. So providing an MP4/MP3 fallback allows JW Player to fallback on HTML5 video tags and present the raw file; i.e., without using the RTMP protocol that is currently Flash-only.

**Comment by jimztercrack** [comment]
You can use vitamio from here: https://www.vitamio.org/en/ and https://github.com/red010182/SwiftVitamioDemo

**Comment by raamdev** [comment]
@jimztercrack It looks like Vitamio is an SDK that can be used when building Android and iOS apps, not a player than can be embedded on a WordPress page that is protected by s2Member.
