### ISSUE TITLE
Does s2Member have a "paywall"?

### ISSUE THREAD

**Issue by brucewsinc** [websharks/s2member-kb#91]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Create Markdown file for this Article (remove `draft-finalized` label, add `pending` label)
- [x] Publish KB Article (remove `pending` label, add `published` label; leave this step for the Project Lead)

---

**Markdown File:** http://wsharks.com/1GIqhd5
**Published KB Article:** http://s2member.com/kb-article/does-s2member-have-paywall/

---

**Comment by jaswsinc** [comment]
Suggestions...

> s2Member's usage of the Membership Options Page can be considered a Paywall. When Users attempt to access restricted content s2Member puts up a "wall" to restrict the content, and redirects the User. The User is sent to the Membership Options Page, which should tell Users about your site's content and show them how to sign up.

With s2Member, you may configure a  "Membership Options Page". This can be considered a Paywall. When Users attempt to access restricted content, s2Member will redirect unauthenticated users to the Membership Options Page. All of this is part of s2Member's Security Gate (aka: Paywall).

See also: https://www.youtube.com/watch?v=2SMp9DYL3nM
See also: https://www.youtube.com/watch?v=iOfiEvR9Bjk

**Comment by brucewsinc** [comment]
@jaswsinc 
> Suggestions...

Thanks! Updated.
