### ISSUE TITLE
If I configure Basic Download Restrictions for unlimited file downloads, are my files still protected by s2Member?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#94]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

- [x] Update link to [How can I bypass the Basic Download Restrictions?](https://github.com/websharks/s2member-kb/issues/104) to use a Live KB Link.

---

**Markdown File:** http://wsharks.com/1GIpwAN
**Published KB Article:** http://s2member.com/kb-article/if-i-configure-basic-download-restrictions-unlimited-file-downloads-are-my-files-still-protected-s2member/

---

**Comment by jaswsinc** [comment]
This is complete and accurate. The only exception would be if you explicitly pass a shortcode attribute, `check_user="no"`. Referencing: http://www.s2member.com/kb/jwplayer-s2stream-shortcodes/#using-s2stream-shortcodes

**Comment by raamdev** [comment]
@jaswsinc Thanks! I added a section to this article. Is this also correct?

> Keep in mind that you must still _enable_ Basic Download Restrictions as described above, even if you're setting `check_user="no"`.

**Comment by jaswsinc** [comment]
> Is this also correct?

Great question. I had to do a quick review to determine. 

---

If you provide a File Download Key, or you set `check_user="no"`, then Basic Download Restrictions are bypassed entirely, and the file will be served **even if you have no Basic Download Restrictions**.

**Comment by raamdev** [comment]
@jaswsinc Thanks for checking on that! :-)

I created a new KB article for this here: [How can I bypass the Basic Download Restrictions?](https://github.com/websharks/s2member-kb/issues/104)

**Comment by jaswsinc** [comment]
Adding the `download-options` tag.
