### ISSUE TITLE
Specific Post/Page Link On Sales/Other pages

### ISSUE THREAD

**Issue by Ashik72** [websharks/s2member-kb#97]
#First of all, its not an issue. Just a suggestion that may get importance on later version of s2Member. 

Specific Post/Page Access Restriction provides links after buying access for a page/post. I came through a situation, where I had to show this link after 2/3 level sales pages. Now there is already a built in class c_ws_plugin__s2member_sp_access and using it its to generate a link. But the problem is, it just generates the access link with all associated info (YEA, MAY BE HERE THIS IS AN ISSUE) and anyone without even buying the access can use this link (this can be slightly avoided with IP restriction). Still I couldn't extend it on other pages.

So I searched for another solution and finally wrote a simple plugin. I started recording last user link and IP on a log file (thanks for the kb article http://www.s2member.com/kb/building-an-api-notification-handler/). As long as recorded IP and user IP match, I wrote a shortcode to  show the link to user. I could've tried array here instead of last IP as it may cause difficulty while multiple sales will happen. However, it was fine with my requirement.

The code is here https://github.com/Ashik72/show-s2member-specific-post-page-buy-now-link-another-page

This script may be improved with some security or may be a complete junk, still it does the work for me. Hope s2 team will bring something amazing later. :)

[Btw, I did it for stripe, not sure about other gateways.]

**Comment by raamdev** [comment]
@Ashik72 Could you please explain what you're trying to achieve here?

Why can't you just use the s2Member Specific Post/Page (Buy Now) shortcode (`s2Member ⥱ Stripe Pro-Forms ⥱ Stripe Specific Post/Page (Buy Now) Forms`) to generate a form that allows users to purchase access to a specific Post/Page? 

After they purchase access, s2Member will automatically email them a special link giving them access to the Post/Page.

**Comment by Ashik72** [comment]
Hi raamdev,

Yea, I generated the form. But beside mail I wanted to show buyer an additional success page and 2/3 more offer pages. Finally on last offer page I wanted to generate the link. It was like a funnel.
